### ISSUE TITLE
Parse failure on .bank <expression> slot <expression>

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#11]
Original code:
```
.define n 3
.bank n+1 slot 1
```
Gives error:
```
file.asm:287: DIRECTIVE_ERROR: .BANK number must be zero or positive.
file.asm:287: ERROR: Couldn't parse ".bank".
```
Looking at parse.c:input_number(), it's hardly comprehensible but it seems it's trying to absorb the "slot 1" into the first expression because it doesn't know to stop. If I add a comma, which looks like it causes a break:
```
.define n 3
.bank n+1, slot 1
```
...then it works.

**Comment by vhelin** [comment]
The latest sources can handle this situation, I guess it's been a while like the problem was addressed
