### ISSUE TITLE
Doc: Incomplete explaination in .SECTION

### ISSUE THREAD

**Issue by Neui** [vhelin/wla-dx#123]
<sup>This is what i always wanted to report... I never got to sending an E.Mail</sup>

https://github.com/vhelin/wla-dx/blob/fcc4dcba97c7573cc517ce7dc9342bca8051b5fe/README#L2208-L2212

The sentence just ends. There is missing something.

**Comment by maxim-zhao** [comment]
Proposal:

> If you replace FREE with SUPERFREE the section will be inserted somewhere in any bank with the same size as bank 0.
