### ISSUE TITLE
Power operator only supports integer exponents

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#137]
The docs say everything is doubles underneath but the implementation of the "^" operator does integer powers of doubles. 

I needed the precision so I trivially changed it to use pow() from <math.h> - is there a reason that is avoided?

**Comment by vhelin** [comment]
On Mon, 8 May 2017 at 17:56, Maxim <notifications@github.com> wrote:

> The docs say everything is doubles underneath but the implementation of
> the "^" operator does integer powers of doubles.
>
> I needed the precision so I trivially changed it to use pow() from
> <math.h> - is there a reason that is avoided?
>

No reason that I'd remember any more. :)

**Comment by vhelin** [comment]
Hmm, I think WLA already calculated the pow in doubles, at least q and v are both doubles, so your fix just makes WLA to use math-lib's pow() function. ???

**Comment by vhelin** [comment]
Oh man, my bad! One cannot do x^y where y is a real number, the loop makes it an integer. I'll add your code to master.

**Comment by maxim-zhao** [comment]
Confusing git workflow meant I managed to submit a PR to my own fork with the bugfix - but your change is identical.
