### ISSUE TITLE
Uninitialised memory causes intermittent errors when using dotted struct members

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#138]
The codepath for handling a dotted struct member does not set the size member, so it gets the value returned by `malloc()` - which is often zero, but not always. This manifested as garbage values for enum members. Assigning zero seemed to help, but maybe a `memset()` after `malloc()` throughout the code would be better?

**Comment by maxim-zhao** [comment]
This is the same as #27.

**Comment by vhelin** [comment]
Thanks!
