### ISSUE TITLE
Error report line numbers are wrong when I nest structs

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#140]
I have a project where errors are reporting line numbers quite far away from the actual line containing the error. I will try to nail down what causes it...

**Comment by nicklausw** [comment]
Which program is reporting the inaccurate errors, the assembler or linker?

**Comment by nicklausw** [comment]
Wait, are you using C-style comments (\/*...*/\)? Some other programs tend to throw away newlines when they come across that and it spans multiple lines.

**Comment by maxim-zhao** [comment]
A little experimenting suggests I "lose" one line every time I nest a struct (!).

```
.struct Word
Lo db
Hi db
.endst
ld a, 1000 ; error on line 5 (correct)
.struct SoundChannel
  Attenuation db
  Tone instanceof Word
.endst
ld a, 1000 ; error on line 9 (off by one)
```

**Comment by maxim-zhao** [comment]
Seems to be caused by the (optional) array size integer following the struct name - it looks like the line number doesn't get incremented when the number is at the end of the line. Adding a number makes it work.

I think the code at pass_1.c:2238 needs to call next_line() if input_number() returned ``INPUT_NUMBER_EOL``.

**Comment by vhelin** [comment]
Thanks for the fix!
