### ISSUE TITLE
It doesn't let me declare a byte array size using references to labels...

### ISSUE THREAD

**Issue by sverx** [vhelin/wla-dx#15]
I mean, for instance this doesn't work:

```
.define MYSIZE somelabel_end-somelabel
.ramsection "RAM" slot 3
  myVar dsb MYSIZE
.ends
```

**Comment by vhelin** [comment]
As my commit https://github.com/vhelin/wla-dx/commit/3f5dd1cd020f484da308f55e9e711d9201d242a8 fixes this issue I'm hitting the close button. If you find there's a bug in the implementation of the fix, please reopen this issue.
