### ISSUE TITLE
 EGLIBC 2.15 complains about functions with attribute warn_unused_result

### ISSUE THREAD

**Issue by cr1901** [vhelin/wla-dx#16]
Compiling with a glibc on Ubuntu (version 2.15) results in a number of warnings (not errors) that are probably harmless, but might be annoying to some users :P. I have listed one of these errors below:

```
pass_1.c:4097:10: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
```

According to [this SO answer](http://stackoverflow.com/questions/7271939/declared-with-attribute-warn-unused-result), this warning is triggered for functions internally declared with the GCC attribute warn_unused_result, when the functions in question are called and subsequently have their return value discarded. Apparently, best practice is to check the return value in some way for these often misused functions :P.

Provided it's not hiding any potential bugs, this of course can be disabled with the flag -Wno-unused-result.

This is more of an FYI than anything. Like it or not, a number of Linux users of this tool probably use GLIBC and the gcc compiler.

**Comment by vhelin** [comment]
Just for the record, I have access to a Linux computer now (Ubuntu 18.04), and I still get lots of warnings like that today. GCC 7.4.0.

/home/vhelin/wla-dx/pass_1.c:5577:3: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
   fgets(k, 254, stdin);
   ^~~~~~~~~~~~~~~~~~~~

I think it might be silly to add code that would handle the return value as is there really any point in that? Could we fix some problematic situations by doing that? Just hiding the warning makes more sense I guess...

**Comment by Neui** [comment]
The return value of `gets` can be used to determine whenever there were an error while reading. I think this should be handled.

**Comment by cr1901** [comment]
@vhelin I also think it should be handled. The "common" idiom nowadays is to do a lightweight `try`/`catch`:

```
err = fgets()
if err {
    return -1;
}
```

So we could add that code to shut the compiler up as a stopgap (and worry about making the errors better later?).

**Comment by vhelin** [comment]
Anyone wants to fix this? :D

**Comment by lhsazevedo** [comment]
I'll give it a try!

**Comment by lhsazevedo** [comment]
Apparently, we should check if the return is equal to the count parameter.
`fread` returns the number of bytes readed. If it's different from count, the end-of-file was reached or a read error ocurred. [Source](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html)

Should I check this instead of NULL?

**Comment by vhelin** [comment]
> Apparently, we should check if the return is equal to the count parameter.

Sounds good!

**Comment by lhsazevedo** [comment]
I'm getting an unsigned compare error after this change

```c   /* read the whole file into a buffer */
if (fread(g_include_in_tmp, 1, file_size, f) != file_size) {
  return FAILED;
}
```

```
warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

Casting `file_size` to `size_t` removes the warning:

```c
if (fread(in_tmp, 1, file_size, f) != (size_t) file_size) {
  return FAILED;
}

```

Is it ok to cast `file_size` before comparing?
If so, should I cast to another type?

**Comment by vhelin** [comment]
I think the cast to size_t should be ok. If someone has a file, in WLA DX's context, that's bigger than size_t, then he/she can program their own assembler. :D

**Comment by vhelin** [comment]
I'll add checks to every fscanf() as well so we can close this issue soonish...

**Comment by vhelin** [comment]
As I don't have access to a compile that'd give warnings about unused return values I'm not 100% sure this issue is now fixed, but we now check the return values of every fread(), fgets() and fscanf(), I'm thinking this issue is solved. If not, feel free to reopen this issue with details.
