### ISSUE TITLE
wla-dx v9.7?

### ISSUE THREAD

**Issue by Drenn1** [vhelin/wla-dx#172]
There've been a fair few changes since v9.6, I think it would be helpful to have a new version so we can use the new features without people needing to build the latest source.

**Comment by Kroc** [comment]
Ditto; and please ensure the docs are up to date.

**Comment by vhelin** [comment]
I published v9.7. When one makes changes to the codebase he should also
make sure the docs are up to date. Updating the docs later, after all the
small and big commits, is a pretty scary and uncertain task especially if
one or two years have passed since the latest release...

**Comment by Drenn1** [comment]
Thanks Ville, you've been busy today I see. :)

**Comment by vhelin** [comment]
Well I was a bit drunk and felt I had the energy to do something. I hope I didn't screw things up much. :) Forgot to update CHANGELOG for the release, but did that right after...
