### ISSUE TITLE
Macros truncate float parameters

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#188]
```
.macro Times100 args n
.db n*100
.endm

  Times100 0.1 ; produces 0, not 10
```

**Comment by vhelin** [comment]
This is partially fixed. When using ARGS and the defines it generates this is now fixed, but if you point to arguments via their numbers e.g. \1 and \2 this remains unfixed. I'll try to fix that next.

**Comment by vhelin** [comment]
This should be fixed now...
