### ISSUE TITLE
Hex macro argument parsing is broken

### ISSUE THREAD

**Issue by Gekkio** [vhelin/wla-dx#194]
Macro arguments that use hex syntax ($) are completely broken in current master version.

wla-gb example:

```asm
.rombanksize $4000
.rombanks 2

.memorymap
  defaultslot 0
  slot 0 start $0000 size $4000
  slot 1 start $4000 size $4000
.endme

.macro hello ARGS wtf
  ld a, wtf
.endm

  hello $80
```

This program should emit an `ld a, $80` instruction, but at least on my machine it emits `ld a, $01`. The actual value depends on global state and what other things have happened recently. For example, in a similar situation in one of my ROMs, wla-gb parses a `$80` argument as `65036`, tries to emit `ld a, 65036` instead of `ld a, $80`, and throws an error.

It seems that the problem is some kind of confusion between the `d` and `parsed_double` global variables.

With some printf debugging I can see these things happen:

1. `pass_1` is collecting macro arguments (after the `/* collect macro arguments */` comment in code)
2. `pass_1` calls `input_number`
3. `input_number` ends up in the branch with a `/* is it a hexadecimal value? */` comment. It parses the hex value and updates `d` but not `parsed_double`.
4. at this point, `q=1 d=128, parsed_double=1.000000`.
5. q=SUCCEEDED, so `redefine` gets called with:
    name="wtf"
    arg=1.000000 **<------ oops**
    type=DEFINITION_TYPE_VALUE
6. `wtf` is now defined incorrectly

**Comment by Gekkio** [comment]
I couldn't figure out how to fix this properly, so I applied this hotfix locally that uses `d` instead of `parsed_double` since I don't need floating point support myself:

https://github.com/Gekkio/wla-dx/commit/2fd42c8823e701da724be0e78eda8a7a224e12f1

**Comment by vhelin** [comment]
Ok, this should be fixed now

**Comment by Gekkio** [comment]
Thanks! It fixed all the error messages, but there's still something that strange in the emitted code. I'll try to get a small reproducible example...looks like it might happen when a macro calls another macro...?

**Comment by Gekkio** [comment]
I don't understand why this happens, but here's an example:

```asm
.rombanksize $4000
.rombanks 2

.memorymap
  defaultslot 0
  slot 0 start $0000 size $4000
  slot 1 start $4000 size $4000
.endme

.macro nops ARGS count
  .repeat count
    nop
  .endr
.endm

.macro hello ARGS arg1 arg2 arg3
  ld a, arg1
  nops arg2
  ld a, arg1
  nops arg3
.endm

  hello $80, 2, 3
  ld b, c
```

Emitted code:

```asm
ld a,$80                ; $0000: $3e $80
nop                     ; $0002: $00
nop                     ; $0003: $00
nop                     ; $0004: $00
ld a,$80                ; $0005: $3e $80
nop                     ; $0007: $00
nop                     ; $0008: $00
nop                     ; $0009: $00
ld b,c                  ; $000a: $41
```

Note the extra NOP in the first chain of nops. It's not a simple off-by-one, because in my actual test ROM I use a quite similar technique, and wla-gb emits 65 NOPs instead of 2. With my dirty workaround patch (which uses `d` instead of `parsed_double`) I get the expected result of 2 and 3 NOPs.

**Comment by vhelin** [comment]
On Sun, Aug 26, 2018 at 8:03 PM Joonas Javanainen <notifications@github.com>
wrote:

> I don't understand why this happens, but here's an example:
>
> .rombanksize $4000.rombanks 2
> .memorymap  defaultslot 0  slot 0 start $0000 size $4000  slot 1 start $4000 size $4000.endme
> .macro nops ARGS count  .repeat count    nop  .endr.endm
> .macro hello ARGS arg1 arg2 arg3  ld a, arg1  nops arg2  ld a, arg1  nops arg3.endm
>   hello $80, 2, 3  ld b, c
>
> Emitted code:
>
> ld a,$80                ; $0000: $3e $80nop                     ; $0002: $00nop                     ; $0003: $00nop                     ; $0004: $00ld a,$80                ; $0005: $3e $80nop                     ; $0007: $00nop                     ; $0008: $00nop                     ; $0009: $00ld b,c                  ; $000a: $41
>
> Note the extra NOP in the first chain of nops. It's not a simple
> off-by-one, because in my actual test ROM I use a quite similar technique,
> and wla-gb emits 65 NOPs instead of 2. With my dirty workaround patch
> (which uses d instead of parsed_double) I get the expected result of 2
> and 3 NOPs.
>

I get the same faulty result here. I'll try to give it a look tomorrow.
Really weird.

**Comment by Gekkio** [comment]
Thanks! It works now
