### ISSUE TITLE
Bug in name value calculation

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#197]
This seems to have been introduced fairly recently, as I was picking up an old project and trying to assemble it again. Here's my minimal repro:
```
.define val1 1

.struct struct2
  y db
.endst

.struct struct1
  ys instanceof struct2 64
.endst

.macro themacro args x
.printt "x = "
.printv dec x
.printt "\n"
.endm

  themacro val1
```
This will print the value 64, not 1 as expected. Rearranging the lines seems to work around it. I'm not sure if my nesting of structs is valid - it is certainly useful.

**Comment by vhelin** [comment]
Have you tried with the latest sources? I just fixed a macro argument
parser bug like this few days ago... :) For me the macro will print 1.

**Comment by maxim-zhao** [comment]
Confirmed, I get the bug with latest code. Paste the end into the Z80 bug exhibition template and I get this
````
>wla-z80 -t main.s 
x = 64
````

**Comment by vhelin** [comment]
Ouch.

I copy pasted your example to the end of "examples/gb-z80/linker_test" and
it printed 1... Hmm, I'll give it a look.

**Comment by maxim-zhao** [comment]
The issue seems to be that input_number() is parsing "val1" and correctly finding a definition for it, and assigning the value to `d` (line 567); but then the code in pass_1() (line 660) uses the value in `parsed_double`, which is a left-over value from earlier lines. I'm super unfamiliar with this code, so I'm not confident to simply assign `parsed_double` at the same time.

**Comment by maxim-zhao** [comment]
My mistake, I was pulling from my repo, not yours... I'll try again...
