### ISSUE TITLE
Addition of LDH A,(C) and LDH (C),A instructions into WLA-GB

### ISSUE THREAD

**Issue by a0r10n** [vhelin/wla-dx#208]
As written in the title. LDH A,(C) and LDH (C),A are very convenient, and implementing them adds 2 lines to 
[opcodes_gb.c](https://github.com/vhelin/wla-dx/files/2606414/opcodes_gb.txt), with no hiccups. I added them in to my own copy, but building anything on my system is difficult (I have gcc on Windows), and if this were included in WLA by default I wouldn't need to rebuild.

Also, it's really convenient.

**Comment by vhelin** [comment]
Thanks for letting me know! I just added the aliases to the sources...
