### ISSUE TITLE
 cmake -G "Unix Makefiles" fails under Linux Mint 17

### ISSUE THREAD

**Issue by sverx** [vhelin/wla-dx#211]
This is probably me being a newbie developer under Linux - I can't install WLA-DX on a Linux Mint 18 box.
cmake -G "Unix Makefiles" fails, saying that 'The C compiler "/usr/bin/cc" is not able to compile a simple test program'.
Which are the requisites? I've got:
cmake 3.5.1
gcc 5.4.0
Thanks!

edit: sorry, I meant Linux Mint 18

**Comment by vhelin** [comment]
I'm not sure at all, but have you tried to install g++ in addition to gcc?

**Comment by Neui** [comment]
This is because by default CMake searches for an C and an C++ compiler when there is no explicit language set in `CMakeLists.txt`. This is actually fixed by my PR #184 but it's currently stalled.

**Comment by sverx** [comment]
> This is because by default CMake searches for an C and an C++ compiler when there is no explicit language set in `CMakeLists.txt`.

makes sense...

Anyway build succeeded - thanks! :)

**Comment by vhelin** [comment]
I added a note to INSTALL saying that one needs gcc, g++, make and cmake to be installed if one wants to compile WLA DX.
