### ISSUE TITLE
Add support for .DL and .DD

### ISSUE THREAD

**Issue by vhelin** [vhelin/wla-dx#22]
.DL = define long word
.DD = define double long word

Is there any need for these as the currently supported CPUs are all 8bit?

**Comment by vhelin** [comment]
Hey, what about support for

.d8 (same as .db)
.d16 (same as .dw)
.d24 (three bytes)
.d32 (four bytes)

??? That would make things simple and clear...

**Comment by nicklausw** [comment]
My only complaint with that is it isn't universal. It'd be a nice alias to the existing db and dw though.

**Comment by cr1901** [comment]
.dl and .dd are more universal. However, .d8-.d64 could certainly alias.

**Comment by vhelin** [comment]
Forgot to mention this issue in the commit, but ea7f00b7bd054eb7308fb43db41f7794807e8a5f ( https://github.com/vhelin/wla-dx/commit/ea7f00b7bd054eb7308fb43db41f7794807e8a5f ) added support for 32-bit .DD, DSD and DDM, which should fix this issue.
