### ISSUE TITLE
Typo of mine in Z80 opcodes

### ISSUE THREAD

**Issue by Kroc** [vhelin/wla-dx#221]
https://github.com/vhelin/wla-dx/blob/0ac4e819d681640d37cacf64c3ef88fbcf5d800c/opcodes_z80.c#L603

Should be:

```c
    { "LD C',L'", 0x4d, 0, 0, 0 }, 
```

(L is a shadow register, I missed the apostrophe)

**Comment by vhelin** [comment]
Fixed, but forgot to mention this bug report (#221) in the commit. Thanks!
