### ISSUE TITLE
Suggestion: Add `.ADDR` as direct alias to `.WORD`

### ISSUE THREAD

**Issue by Kroc** [vhelin/wla-dx#222]
Other assemblers (such as CA65) have `.ADDR` as an alias to `.WORD` purely for readability within code making it easier to see when, in tables of data, values are arbitrary vs. ROM/RAM locations.

I can't say whether 65816 code should use 2-bytes for `.ADDR` or 3, but an `.LADDR` directive could handle the long-address form accordingly.

**Comment by vhelin** [comment]
I just checked CA65's documentation and it seems that .ADDR is 16-bit while .FARADDR is 24-bit. But sure, I can add these to WLA.
