### ISSUE TITLE
Add EXPORT to .DEFINE or create a new directive that defines and exports at the same time

### ISSUE THREAD

**Issue by vhelin** [vhelin/wla-dx#224]
Currently you need to type two lines to define and export a definition:

.DEFINE ID 1
.EXPORT ID

It would be convenient if somethine as follows would work

.DEFINE ID 1 EXPORT

Or perhaps

.DEFEXP ID 1

?

**Comment by Ramsis-SNES** [comment]
WLA DX just keeps getting better and better. Thanks again! :D

**Comment by vhelin** [comment]
You're welcome. :) I'm currently bored and don't feel like starting a new project, but coding WLA DX forward feels nice.
