### ISSUE TITLE
Fail to compile with clang on mac

### ISSUE THREAD

**Issue by tsupplis** [vhelin/wla-dx#226]
In file included from /Users/thierry/Projects/Devel/wla-dx/pass_1.c:863:
/Users/thierry/Projects/Devel/wla-dx/decode_spc700.c:630:7: error: no newline at
      end of file [-Werror,-Wnewline-eof]
break;

**Comment by tsupplis** [comment]
adding new line at the end of the file resolves the problem

**Comment by vhelin** [comment]
Can you tell us which file is causing such problems, and I'll fix it to
GitHub?

**Comment by tsupplis** [comment]
wla-dx/decode_spc700.c

**Comment by vhelin** [comment]
Thanks, I added a new line to the end of decode_spc700.c!

**Comment by tsupplis** [comment]
problem fixed, thank you

**Comment by cr1901** [comment]
@vhelin For future reference, the "newline at end of file" requirement comes from `-pedantic-errors`; for whatever historical reason, ANSI C requires files to be terminated with newlines.

**Comment by vhelin** [comment]
> @vhelin For future reference, the "newline at end of file" requirement comes from `-pedantic-errors`; for whatever historical reason, ANSI C requires files to be terminated with newlines.

Then it's weird that GCC 7.4.0 on my computer didn't complain about it...

**Comment by cr1901** [comment]
Hrm interesting... wonder why that it's not caught by gcc... I mean, wouldn't be the first time compilers don't do what I expect :P.

I've def ran into said error before in gcc, but not w/ decode_spc700, and Idk if I've used 7.4.0...
