### ISSUE TITLE
WLALINK should discard SUPERFREE sections

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#234]
It seems the `-d` option only causes unreferenced `FREE` and `SEMIFREE` sections to be discarded, as is written in the docs. I think unreferenced `SUPERFREE` sections should be discarded too.

**Comment by vhelin** [comment]
Thanks for the report, unreference SUPERFREE sections should now be discarded if -d is used...

BTW, could someone who is familiar with hashmaps and labels in WLA DX update "wlalink/discard.c"'s label freeing to work properly (remove labels also from hashmaps)? I can also try to do that, but I'm not 100% sure of what to do...

**Comment by vhelin** [comment]
Hey, have you had time to check out the latest sources?

**Comment by maxim-zhao** [comment]
I just tried it - but a few other issues are getting in the way, I'll create some new issues shortly...

**Comment by maxim-zhao** [comment]
Works On My Machine 👍
