### ISSUE TITLE
wlalink crashes in test suite on MinGW/CL.exe

### ISSUE THREAD

**Issue by cr1901** [vhelin/wla-dx#24]
As of commit dee81a5, wlalink will crash while compiling the z80 example sms.o (in examples/z80/sms_test). I have verified that it will crash with executables compiled both using a CL.exe clone and MinGW. I'll test Unix when I have the chance.

**Comment by vhelin** [comment]
I guess this it not an issue any more?

**Comment by cr1901** [comment]
@vhelin `run_tests.sh` works on my end :). Including the previously-crashing `examples/z80/sms_test`. I think we can close!
