### ISSUE TITLE
Unary tilde (~) does not generate the correct results.  Suggest it should act as NOT.

### ISSUE THREAD

**Issue by SavagePencil** [vhelin/wla-dx#264]
When a unary ~ is used, it does not perform any operation on the values provided.  Suggest it become a shorthand for NOT, currently achieved by doing $FF ~ VAL.

Repro:

```
.DEFINE X $20
.DEFINE Y $40

ld a, $FF
and ~(X | Y)
```

This should result in `$9F`, but instead results in `$60`.  The opcode emitted for the and instruction is for "and $60".

**Comment by vhelin** [comment]
Ok, the latest sources should handle unary tilde as NOT. Can you test it? Thanks!

**Comment by SavagePencil** [comment]
Can confirm that unary ~ is now providing the correct behavior in latest.  Thank you!
