### ISSUE TITLE
Macro constant to insert current macro name

### ISSUE THREAD

**Issue by Kroc** [vhelin/wla-dx#284]
To help with the ease of making macros that use private labels, and flexibility in renaming macros, could we have a macro constant (`\...`) for inserting the current macro name? I would suggest `\.` but you may have your own feeling on this.

![image](https://user-images.githubusercontent.com/142650/73267585-40d6a300-41d1-11ea-991b-f24168ec7263.png)

**Comment by vhelin** [comment]
Ok, I hope it works now.

**Comment by Kroc** [comment]
Compiling to test; does this include the "." in the output? (assumedly not)

**Comment by Kroc** [comment]
WFM 👍
