### ISSUE TITLE
is .ENDST case sensitive?

### ISSUE THREAD

**Issue by sverx** [vhelin/wla-dx#306]
I can correctly close a
`.dstruct Name instanceof definition values`
if I write
`.ENDST`
but not if I write
`.endst`

Is it supposed to be case sensitive?

**Comment by vhelin** [comment]
I found one strcmp() in the code that should have been strcaselesscmp() instead. It might work now... Good find!

**Comment by sverx** [comment]
I just stumbled upon it, I didn't actively seek it!

**Comment by sverx** [comment]
Fixed in last commit. Thanks! :+1:
