### ISSUE TITLE
Macros broken?

### ISSUE THREAD

**Issue by shewitt-au** [vhelin/wla-dx#308]
I'm new to WLA-DX but this looks like it should work:

```
.MACRO aaa ARGS SZ
    NOP
.ENDM
aaa 1
```
I get this error:

> wla-65816  -o objs/main.o main.asm
> main.asm:61: ERROR: Unknown symbol "1".

Version info:

> wla-65816  -o objs/main.o main.asm
> main.asm:61: ERROR: Unknown symbol "1".

**Comment by shewitt-au** [comment]
Looks like I'm an idiot. Indentation is important. Sorry for the spam.

**Comment by vhelin** [comment]
No worries. :) Yeah, it's an old custom to have labels start at the beginning of the line...
