### ISSUE TITLE
Muting warnings for cross-slot calculations

### ISSUE THREAD

**Issue by Drenn1** [vhelin/wla-dx#314]
As discussed in #173, doing calculations involving labels from different slots causes a warning to be printed:

```build/seasons.o: code/bank0.s:1821: COMPUTE_STACK: The passed on SLOT changed from $0 to $2. This might have no effect, but just to let you know. Please check that the result of this calculation is correct.```

The warning makes sense and is useful. But there are legitimate reasons to need to do this, and having this warning printed every time my code is assembled clutters the console output. Could we have an option to mute this? Like "-Wno-slot-calc-check" in wlalink or something like that?

**Comment by vhelin** [comment]
The reason I made WLALINK to give that error is that I'm not 100% sure that, in the case that happens, 100% of the calculations will be correct. :) They might be, but I'm just not sure myself...

Adding a switch to silence such warnings is pretty simple, though.

**Comment by vhelin** [comment]
I think I removed these warnings so this issue should be closed... :)
