### ISSUE TITLE
Allow Makefile rules to generate when incbin fails

### ISSUE THREAD

**Issue by bazzinotti** [vhelin/wla-dx#319]
Hello Ville and co!

I have wla-dx to allow Makefile rules generation even when "incbin" files are not found. In my usage, this was useful when I generated the Makefile before generating other assets.

If this interests you, let's chat or ask me to submit the PR.

**Comment by vhelin** [comment]
Sounds good for me! Just submit a PR and I'll approve it. :)

**Comment by vhelin** [comment]
Ah, you already did submit the PR - I'll have a look at it.
