### ISSUE TITLE
Unknown symbol

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [vhelin/wla-dx#326]
I wanna play music on my SNES game but the compiler says that there is an unknown symbol so it cannot compile, why I'm having this error?

**Comment by vhelin** [comment]
Well, can you post here the line of the source code that is giving WLA problems (and the full error message)?

**Comment by LucianoTheWindowsFan** [comment]
Here it is:
` ; SNES Initialization Tutorial code
 ; This code is in the public domain.
 
 .include "Header.inc"
 .include "Snes_Init.asm"
.INCBIN "bibendum.bin"
 
 ; These definitions are needed to satisfy some lines in "Snes_Init.asm".
 .define BG1MoveH $7E1A25
 .define BG1MoveV $7E1A26
 .define BG2MoveH $7E1A27
 .define BG2MoveV $7E1A28
 .define BG3MoveH $7E1A29
 .define BG3MoveV $7E1A2A
 
 ; Needed to satisfy interrupt definition in "Header.inc".
 VBlank:
   rti
 
 .define AUDIO_R0 $2140
 .define AUDIO_R1 $2141
 .define AUDIO_R2 $2142
 .define AUDIO_R3 $2143
 
 .define XY_8BIT $10
 .define A_8BIT  $20
 
 .define musicSourceAddr $00fd
 
 ; The SPC file from which we read our data.
 .define spcFile "test000.spc"
 
 ; The address in SPC RAM where we put our 15-byte startup routine.
 .define spcFreeAddr $ffa0
 
 ; The first half of the saved SPC RAM from the SPC file.
 .bank 1
 .section "musicData1"
 spcMemory1: .incbin spcFile skip $00100 read $8000
 .ends
 
 ; The second half of the saved SPC RAM from the SPC file.
 .bank 2
 .section "musicData2"
 spcMemory2: .incbin spcFile skip $08100 read $8000
 .ends
 
 .bank 0
 .section "MainCode"
 
 ; The rest of the saved SPC state from the SPC file.
 dspData:  .incbin spcFile skip $10100 read $0080
 audioPC:  .incbin spcFile skip $00025 read $0002
 audioA:   .incbin spcFile skip $00027 read $0001
 audioX:   .incbin spcFile skip $00028 read $0001
 audioY:   .incbin spcFile skip $00029 read $0001
 audioPSW: .incbin spcFile skip $0002a read $0001
 audioSP:  .incbin spcFile skip $0002b read $0001
 
 Start:
     ; Initialize the SNES.
     Snes_Init
 
     jsr LoadSPC
 
     ; Set the background color to green.
     sep     #$20        ; Set the A register to 8-bit.
     lda     #%10000000  ; Force VBlank and set brightness to 0%.
     sta     $2100
     lda     #%11100000  ; Load the low byte of the green background color.
     sta     $2122
     lda     #%00000000  ; Load the high byte of the green background color.
     sta     $2122
     lda     #%00001111  ; End VBlank, setting brightness to 100%.
     sta     $2100
 
     ; Loop forever.
 Forever:
     jmp Forever
 
 .macro sendMusicBlockM ; srcSeg srcAddr destAddr len
     ; Store the source address \1:\2 in musicSourceAddr.
     sep     #A_8BIT
     lda     #\1
     sta     musicSourceAddr + 2
     rep     #A_8BIT
     lda     #\2
     sta     musicSourceAddr
 
     ; Store the destination address in x.
     ; Store the length in y.
     rep     #XY_8BIT
     ldx     #\3
     ldy     #\4
     jsr     CopyBlockToSPC
 .endm
 
 .macro startSPCExecM ; startAddr
     rep     #XY_8BIT
     ldx     #\1
     jsr     StartSPCExec
 .endm
 
 LoadSPC:
     jsr     CopySPCMemoryToRam
 
     stz     $4200   ; Disable NMI
     sei             ; Disable IRQ
 
     ; Copy RAM between 0x0002 and 0xffc0.
     sendMusicBlockM $7f $0002 $0002 $ffbe
 
     ; Build code to initialize registers.
     jsr     MakeSPCInitCode
 
     ; Copy init code to some region of SPC memory that we hope isn't in use.
     sendMusicBlockM $7f $0000 spcFreeAddr $0016
 
     ; Initialize DSP registers.
     jsr     InitDSP
 
     ; Start SPC execution at init code region.
     startSPCExecM spcFreeAddr
 
     cli             ; Enable IRQ
     sep     #A_8BIT ; Enable NMI
     lda     #$80
     sta     $4200
 
     rts
 
 CopySPCMemoryToRam:
     ; Copy music data from ROM to RAM, from the end backwards.
     rep   #XY_8BIT        ; xy in 16-bit mode.
     ldx.w #$7fff           ; Set counter to 32k-1.
 -   lda.l spcMemory1,x     ; Copy byte from first music bank.
     sta.l $7f0000,x
     lda.l spcMemory2,x     ; Copy byte from second music bank.
     sta.l $7f8000,x
     dex
     bpl -
     rts
 
 InitDSP:
     rep     #XY_8BIT            ; x and y in 16-bit mode
     ldx     #$0000              ; Reset DSP address counter.
 -
     sep     #A_8BIT
     txa                         ; Write DSP address register byte.
     sta     $7f0100             
     lda.l   dspData,x           ; Write DSP data register byte.
     sta     $7f0101             
     phx                         ; Save x on the stack.
 
     ; Send the address and data bytes to the DSP memory-mapped registers.
     sendMusicBlockM $7f $0100 $00f2 $0002
 
     rep     #XY_8BIT            ; Restore x.
     plx
 
     ; Loop if we haven't done 128 registers yet.
     inx
     cpx     #$0080
     bne     -
     rts
 
 MakeSPCInitCode:
     ; Constructs SPC700 code to restore the remaining SPC state and start
     ; execution.
 
     ; The code we want to construct:
     ; Move 00 byte to 00.
     ; Move 01 byte to 01.
     ; Move s value into s.
     ; Push PSW value.
     ; Move a value into a.
     ; Move x value into x.
     ; Move y value into y.
     ; Pull PSW value.
     ; Jump to saved program counter location.
 
     sep     #A_8BIT
 
     ; Push [01] value to stack.
     lda.l   $7f0001
     pha
 
     ; Push [00] value to stack.
     lda.l   $7f0000
     pha
 
     ; Write code to set [00] byte.
     lda     #$8f        ; mov dp,#imm
     sta.l   $7f0000
     pla
     sta.l   $7f0001
     lda     #$00
     sta.l   $7f0002
 
     ; Write code to set [01] byte.
     lda     #$8f        ; mov dp,#imm
     sta.l   $7f0003
     pla
     sta.l   $7f0004
     lda     #$01
     sta.l   $7f0005
 
     ; Write code to set s.
     lda     #$cd        ; mov x,#imm
     sta.l   $7f0006
     lda.l   audioSP
     sta.l   $7f0007
     lda     #$bd        ; mov sp,x
     sta.l   $7f0008
 
     ; Write code to push psw
     lda     #$cd        ; mov x,#imm
     sta.l   $7f0009
     lda.l   audioPSW
     sta.l   $7f000a
     lda     #$4d        ; push x
     sta.l   $7f000b
 
     ; Write code to set a.
     lda     #$e8        ; mov a,#imm
     sta.l   $7f000c
     lda.l   audioA
     sta.l   $7f000d
 
     ; Write code to set x.
     lda     #$cd        ; mov x,#imm
     sta.l   $7f000e
     lda.l   audioX
     sta.l   $7f000f
 
     ; Write code to set y.
     lda     #$8d        ; mov y,#imm
     sta.l   $7f0010
     lda.l   audioY
     sta.l   $7f0011
 
     ; Write code to pull psw.
     lda     #$8e        ; pop psw
     sta.l   $7f0012
 
     ; Write code to jump.
     lda     #$5f        ; jmp labs
     sta.l   $7f0013
     rep     #A_8BIT
     lda.l   audioPC
     sep     #A_8BIT
     sta.l   $7f0014
     xba
     sta.l   $7f0015
     rts
 
 .macro waitForAudio0M
 -
     cmp     AUDIO_R0
     bne     -
 .endm
 
 CopyBlockToSPC:
     ; musicSourceAddr - source address
     ; x - dest address
     ; y - count
 
     ; Wait until audio0 is 0xbbaa
     sep     #A_8BIT
     lda     #$aa
     waitForAudio0M
 
     ; Send the destination address to AUDIO2.
     stx     AUDIO_R2
 
     ; Transfer count to x.
     phy
     plx
 
     ; Send $01cc to AUDIO0 and wait for echo.
     lda     #$01
     sta     AUDIO_R1
     lda     #$cc
     sta     AUDIO_R0
     waitForAudio0M
 
     ; Zero counter.
     ldy     #$0000
 
 CopyBlockToSPC_loop:
     ; Load the high byte of a with the destination byte.
     xba
     lda     [musicSourceAddr],y
     xba
     
     ; Load the low byte of a with the counter.
     tya
 
     ; Send the counter/byte.
     rep     #A_8BIT
     sta     AUDIO_R0
     sep     #A_8BIT
 
     ; Wait for counter to echo back.
     waitForAudio0M
 
     ; Update counter and number of bytes left to send.
     iny
     dex
     bne     CopyBlockToSPC_loop
 
     ; Send the start of IPL ROM send routine as starting address.
     ldx     #$ffc9
     stx     AUDIO_R2
     
     ; Clear high byte.
     xba
     lda     #0
     xba
 
     ; Add a value greater than one to the counter to terminate.
     clc
     adc     #$2
 
     ; Send the counter/byte.
     rep     #A_8BIT
     sta     AUDIO_R0
     sep     #A_8BIT
 
     ; Wait for counter to echo back.
     waitForAudio0M
 
     rts
 
 StartSPCExec:
     ; Starting address is in x.
 
     ; Wait until audio0 is 0xbbaa
     sep     #A_8BIT
     lda     #$aa
     waitForAudio0M
 
     ; Send the destination address to AUDIO2.
     stx     AUDIO_R2
 
     ; Send $00cc to AUDIO0 and wait for echo.
     lda     #$00
     sta     AUDIO_R1
     lda     #$cc
     sta     AUDIO_R0
     waitForAudio0M
 
     rts
 
 .ends`

**Comment by vhelin** [comment]
Uhh, something must have gone wrong in copying the code here as I don't see

-lda.l

anywhere near line 136... Did you copy and paste the code from somewhere else? If you really have

-lda.l

on that line, put one space after the minus, does that help? I'm assuming it's a local label in this case (the minus)...

**Comment by LucianoTheWindowsFan** [comment]
Tried it, didn't work, it seems like it was for an older version, could you convert it to work on newer versions?

**Comment by vhelin** [comment]
Put all the files available somewhere and I can take a look at it as a whole... This copy pasted version I cannot convert as it contains too many white space problems I'm sure are not in the original source file.

**Comment by LucianoTheWindowsFan** [comment]
I tried it without the SPC700 code, it worked! could you give me a more compatible version of the SPC700 code.¿?

**Comment by LucianoTheWindowsFan** [comment]
Tries it win the space, didn't work, tried it without the music code, it worked! what's wrong with it then?

**Comment by vhelin** [comment]
I don't see any SPC700 code in this file, only 65816 code... If you can give me a link to the whole project I can take a look at it.

**Comment by Neui** [comment]
> 
> 
> Uhh, something must have gone wrong in copying the code here as I don't see
> 
> -lda.l
> 
> anywhere near line 136... Did you copy and paste the code from somewhere else? If you really have
> 
> -lda.l
> 
> on that line, put one space after the minus, does that help? I'm assuming it's a local label in this case (the minus)...

It is (likely) on the line with `-lda.l spcMemory1,x ; Copy byte from first music bank.` since `-` is also used to create an bulled point.

Honestly, this is out of scope for the WLA-DX project, since it is just an assembler (with an linker), not an code/program repository of the architectures it supports.

**Comment by vhelin** [comment]
I fixed all white space problems, removed .INCLUDEs and .INCBINs as I don't have them, added a SNES memory map, and added that minus to line 136:

$ ./binaries/wla-65816.exe -o joo.o joo
DISCARD: joo: Discarding an empty section "musicData1".
DISCARD: joo: Discarding an empty section "musicData2".

-> assembles just fine.

Which version of WLA is the original poster using here? I'm using the latest 9.11a in GitHub...

**Comment by vhelin** [comment]
> It is (likely) on the line with `-lda.l spcMemory1,x ; Copy byte from first music bank.` since `-` is also used to create an bullet point in MarkDown (so you don't find the `-lda.l` but `lda.l` with an bullet in front of it).
> 
> Honestly, this is out of scope for the WLA-DX project, since it is just an assembler (with an linker), not an code/program repository of the architectures it supports.

I also assume that

- lda.l ...

works and

-lda.l doesn't work...

**Comment by vhelin** [comment]
Also make sure that the minus is at the very beginning of that line so it's interpreted as a label. Otherwise this doesn't work, if you have white space on the left side of that minus...

**Comment by LucianoTheWindowsFan** [comment]
I used

> I fixed all white space problems, removed .INCLUDEs and .INCBINs as I don't have them, added a SNES memory map, and added that minus to line 136:
> 
> $ ./binaries/wla-65816.exe -o joo.o joo
> DISCARD: joo: Discarding an empty section "musicData1".
> DISCARD: joo: Discarding an empty section "musicData2".
> 
> -> assembles just fine.
> 
> Which version of WLA is the original poster using here? I'm using the latest 9.11a in GitHub...

I used ver 9.10

**Comment by vhelin** [comment]
Here you can download the latest EXEs for Windows:

https://dev.azure.com/villehelin0486/villehelin/_build/results?buildId=163&view=artifacts&type=publishedArtifacts

If that doesn't work, email me that source file (ville dot helin at gmail dot com) and I can take a look at how you are using the whitespace in that file...

**Comment by LucianoTheWindowsFan** [comment]
> Here you can download the latest EXEs for Windows:
> 
> https://dev.azure.com/villehelin0486/villehelin/_build/results?buildId=163&view=artifacts&type=publishedArtifacts
> 
> If that doesn't work, email me that source file (ville dot helin at gmail dot com) and I can take a look at how you are using the whitespace in that file...

Tried new version, didn't work.

**Comment by vhelin** [comment]
Can't help you more unless you start emailing me the files... Or upload them to some file share service and post a link to that here...

**Comment by LucianoTheWindowsFan** [comment]
> Can't help you more unless you start emailing me the files... Or upload them to some file share service and post a link to that here...

the download works, i meant the asm didn't work.

**Comment by LucianoTheWindowsFan** [comment]
> Put all the files available somewhere and I can take a look at it as a whole... This copy pasted version I cannot convert as it contains too many white space problems I'm sure are not in the original source file.

Here's the file
[code.txt](https://github.com/vhelin/wla-dx/files/4814943/code.txt)

**Comment by vhelin** [comment]
None of the labels in that file start at the beginning of the line, they all have one space on the left side of them...

**Comment by vhelin** [comment]
So, for example line 137. What you have now is

" -  lda.l spcMemory1,x     ; Copy byte from first music bank."

but for it to work it needs to be

"-  lda.l spcMemory1,x     ; Copy byte from first music bank."

(remove the quotation marks)

**Comment by vhelin** [comment]
Actually, now that I think of this, it might be possible to enhance the preprocessor to handle -/--/--- and +/++/+++ local labels when they are not at the beginning of the line?

**Comment by LucianoTheWindowsFan** [comment]
> - lda.l spcMemory1,x ; Copy byte from first music bank.

Tried it, still didn't work.

**Comment by vhelin** [comment]
Here you can download the new Windows EXEs. It should work now even with the white spacing in your code.txt

https://dev.azure.com/villehelin0486/villehelin/_build/results?buildId=166&view=artifacts&type=publishedArtifacts

**Comment by LucianoTheWindowsFan** [comment]
> Here you can download the new Windows EXEs. It works now even with the white spacing in your code.txt
> 
> https://dev.azure.com/villehelin0486/villehelin/_build/results?buildId=166&view=artifacts&type=publishedArtifacts

Tried it, it worked, but when I test it, it black screened and no audio could be heard.

**Comment by vhelin** [comment]
That's something I cannot help you with as I didn't write that code...

**Comment by LucianoTheWindowsFan** [comment]
Source Code:
[https://en.wikibooks.org/wiki/Super_NES_Programming/Loading_SPC700_programs#Complete_Source_Code](https://en.wikibooks.org/wiki/Super_NES_Programming/Loading_SPC700_programs#Complete_Source_Code)

**Comment by vhelin** [comment]
Perhaps you need to ask the person who wrote that code?

**Comment by vhelin** [comment]
I haven't written a single line of code for the SNES so I have no idea...
