### ISSUE TITLE
wlalink: symbol file name generation incorrect

### ISSUE THREAD

**Issue by alasher** [vhelin/wla-dx#329]
I noticed something peculiar when generating the WLA symbol files, sometimes they would strangely be named only `.sym`, I was only able to find them after checking `git status`. I dove into the code and found the problem: the code that modifies the file extension to `.sym` finds the _first_ dot character in the string. But really, we want the _last_ dot. My issue was I was using the current-directory syntax for my output file, ie. `./program.gb`.

While looking through this code, I noticed another problem: the new `name` array we made is only length 256, so if the `outname`'s length happens to be greater than this, it would write outside the bounds of the array. Yikes.

I decided to fix both problems as they were pretty simple, I will submit a pull request referencing this issue.

**Comment by vhelin** [comment]
Good work! Thanks for the patch!
