### ISSUE TITLE
Sort the directives alphabetically in the documentation

### ISSUE THREAD

**Issue by vhelin** [vhelin/wla-dx#369]
This should be an easy fix for people with lots of patience. :) The directives in the docs are now listed in pretty random order. Reordering them alphabetically would make searching and reading much easier...

**Comment by vhelin** [comment]
The file that needs that work: doc/asmdiv.rst

**Comment by lhsazevedo** [comment]
Hmm, I think this has been solved

**Comment by vhelin** [comment]
True, let's close it
