### ISSUE TITLE
Reserve checksum and complement check bytes

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#37]
In wla-gb, I have a very large section (2 kb, although that doesn't really relate to this,) and the beginning of it gets overwritten because it starts at where the checksum + complement check will be.

Looking in the source, there doesn't seem to be a good way to reserve these bytes without giving an absolute value which, while it fixes the problem, also gets overwritten and looks ugly.

Uh...any ideas?

**Comment by vhelin** [comment]
My suggestion: if the user makes the linker to calculate checksum etc., the
linker should reserve those bytes itself before it places the sections.
I.e., a new feature for me to implement. :)

**Comment by nicklausw** [comment]
Wouldn't it just be a case of reversing the order of placement of checksums and sections? (At least, for this case in specific).

**Comment by vhelin** [comment]
Yeah well, one needs all the data placed into the output before one can
calculate the checksum. :)

**Comment by nicklausw** [comment]
It seems I've forgotten how checksums work.

**Comment by vhelin** [comment]
Hey, can you test the latest sources - I made the checksummers reserve the bytes, but don't have the time to test them thoroughly.

**Comment by nicklausw** [comment]
Works. Thanks!
