### ISSUE TITLE
Make g_inz and g_ind local vars when possible

### ISSUE THREAD

**Issue by vhelin** [vhelin/wla-dx#375]
In the assembler global vars g_inz and g_ind are used all over the place instead of local vars. Replace all uses of them both with local vars when possible.

**Comment by lhsazevedo** [comment]
We can make a list of good candidates to local conversion and post here so we can label this as a good-first-issue, what do you think?

**Comment by vhelin** [comment]
Anything that helps. :) But the issue is in pass_1.c and decode_*.c files - just searching for g_ind/g_inz there will give you lots of opportunities for fixes. The decode_*.c files might have to be done at the same time as they are linked to the loop in pass_1.c...

**Comment by vhelin** [comment]
decode.c now needs this treatment

**Comment by lhsazevedo** [comment]
I would like to do that, can you assign me to this issue?
