### ISSUE TITLE
Documentation is missing its title

### ISSUE THREAD

**Issue by vhelin** [vhelin/wla-dx#389]
If I go to https://wla-dx.readthedocs.io/en/latest/ is see that the title in the tab is "\<no title\> - wla-dx 9.12a documentation" (also on Google search), and on the web page is reads: "Docs » \<no title\>"

**Comment by lhsazevedo** [comment]
Just built locally, title Ok. Maybe it's something related to ReadTheDocs?


![screenshot](https://user-images.githubusercontent.com/7695608/127944627-db34d1fe-eaa7-48f0-b650-b79e76ae10eb.png)

**Comment by vhelin** [comment]
Just visited readthedocs.io, now it looks like this - still broken

![image](https://user-images.githubusercontent.com/6417746/128251275-46cb6765-82e5-42cd-94cc-898fb81fdc2f.png)

I guess ReadTheDocs is somehow not working properly, perhaps they use some special version of sphinx, but this is still an (tiny) issue. Perhaps we need to modify the document sources somehow differently to get ReadTheDocs to work? Perhaps someone knows what's going on? :)

**Comment by sverx** [comment]
I can't see any problem. This is how it appears to me (Vivaldi, on Linux)

![image](https://user-images.githubusercontent.com/6738932/185232582-776882fb-ba67-42bf-b280-7c64511d282a.png)

**Comment by vhelin** [comment]
I'm also seeing this at the moment

![image](https://user-images.githubusercontent.com/6417746/185248485-9a51a5c5-234c-4d9b-aab6-85089aa3fb6d.png)

I guess when I some time ago went and did something to the read-the-docs settings accidentally solved this issue (made the robots to use a newer version of some tools) as it seems to be ok now.
