### ISSUE TITLE
.FAIL exit code

### ISSUE THREAD

**Issue by lajohnston** [vhelin/wla-dx#395]
Hi there,

When using the .FAIL directive would it be possible for wla-dx to exit with an error code? I'm using .FAIL when detecting an error condition at assembly time but my build script isn't able to detect this and so continues with other commands like running wla-link.

Lee

**Comment by vhelin** [comment]
Good suggestion, I'll implement it right away...

**Comment by lajohnston** [comment]
Great, thanks! :)
