### ISSUE TITLE
Right curly brace ("}") no longer allowed in strings? 

### ISSUE THREAD

**Issue by SolraBizna** [vhelin/wla-dx#413]
The following trivial source file:

```asm
.DB "}"
```

Now gives the following error, with all of the architectures I tried:

```
test.65c:1: INPUT_NUMBER: String wasn't terminated properly.
test.65c:1: ERROR: Couldn't parse ".DB".
```

This error appears to occur when a `}` occurs anywhere in a `.DB` string.

**Comment by vhelin** [comment]
I found some weird curly braces handling in parse.c, and couldn't figure out why it was there so I removed it, which should fix this issue. Perhaps it was part of {\@+1} handling in .MACROs one time, but this was inside a string ("") and didn't do the things .MACRO parsing would require, like a half finished implementation.

I hope I didn't break anything. :D

**Comment by SolraBizna** [comment]
Confirmed fixed. Thanks!
