### ISSUE TITLE
Binaries path in the test runner

### ISSUE THREAD

**Issue by lhsazevedo** [vhelin/wla-dx#427]
The install guide instructs to create a build directory, and the binaries are placed on `build/binaries`:
https://github.com/vhelin/wla-dx/blob/3f5dd1cd020f484da308f55e9e711d9201d242a8/README.md#L52-L53

However, the test runner expects binaries to be in the binaries folder at the root of the project:
https://github.com/vhelin/wla-dx/blob/3f5dd1cd020f484da308f55e9e711d9201d242a8/run_tests.sh#L24

Experienced developers can get around this issue easily, but it can be challenging for beginners.

Maybe we can resolve this by updating the test runner to expect binaries in the build folder, or both.

**Comment by vhelin** [comment]
> Maybe we can resolve this by updating the test runner to expect binaries in the build folder, or both.

Hmm I've actually never taken the "mkdir build ; cd build ; cmake .." route, I've just issued "cmake -G "Unix Makefiles"" and then "make" in the main dir, and the executables appear in the binaries folder at the root... :) I don't remember who wrote that install guide...

That said, IMO if the test runner can support both, ./binaries and ./build/binaries, that'd be good?
