### ISSUE TITLE
Incorrect calculation of label arithmetic 

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#443]
I've bisected to revision 3f5dd1cd020f484da308f55e9e711d9201d242a8 which introduced a change that breaks my code.

Currently here:

https://github.com/maxim-zhao/zexall-sms/blob/master/source/zexall.sms.asm#L1807

```
.section "Test harness" free
TestCode:
    ; some code...
@InstructionUnderTest:
    .dsb 4, 0
    ; more code...
.define OffsetOfInstructionUnderTest TestCode@InstructionUnderTest - TestCode
```

The idea is to find the difference between the labels for use elsewhere to self-modify the code after it is copied from ROM to RAM. Older versions correctly compute it as $17 but revision 3f5dd1cd020f484da308f55e9e711d9201d242a8 onwards emit these symbols:

```
00:2abc TestCode
00:2ad3 TestCode@InstructionUnderTest
...
00000e31 OffsetOfInstructionUnderTest
```

**Comment by vhelin** [comment]
I made this (GB-Z80 code) to test the issue:

```
TestCode:
        nop
        nop
        nop
        nop
        nop
        nop
@InstructionUnderTest:
        .dsb 4, 0
        nop
        nop
        nop
        nop

        .define OffsetOfInstructionUnderTest TestCode@InstructionUnderTest - TestCode

        .db "06>"               ; @BT TEST-06 06 START
        .db OffsetOfInstructionUnderTest ; @BT 06
        .db "<06"                        ; @BT END
```

... and the test passed. So I think I need two things to be able to solve this problem:

1. Which WLA are you using? Z80? 65816?
2. What code is there in "; some code..." and "; more code..." as those could also make the label delta calculation to break...

**Comment by maxim-zhao** [comment]
1. Z80
2. See my code at the link.. it's mostly stack operations.

**Comment by vhelin** [comment]
Ok, I copied essential bits and code lines to my test, and here's what came out:

[labels]
00:0133 TestCode
00:014a TestCode@InstructionUnderTest

[definitions]
00000017 OffsetOfInstructionUnderTest

... ???

**Comment by vhelin** [comment]
[delta_test.zip](https://github.com/vhelin/wla-dx/files/7360709/delta_test.zip)

If you run this test on your computer, does TEST-06 pass?

**Comment by maxim-zhao** [comment]
It does pass. If I make the section free then I get this:

```
main.o: main.s:181: COMPUTE_PENDING_CALCULATIONS: Result (-183/$ffffff49) of a computation is out of 8-bit range.
```

If I change the test to this:

```
        .db "06>"               ; @BT TEST-06 06 START
        .dw OffsetOfInstructionUnderTest ; @BT 17 00
        .db "<06"                        ; @BT END
```

Then I get this:

```
Test "TEST-06" FAILED - Bytes that don't match: 1 (GOT: $49 EXPECTED: $17), 2 (GOT: $ff EXPECTED: $00)
```

Which looks to me like free sections are related to the issue.

**Comment by vhelin** [comment]
I think I found the reason, but not related to section types. Don't know why FORCE .SECTION works and FREE doesn't, but it seems that stack.c:data_stream_parser_parse() doesn't understand child labels and thus the behaviour is kinda random with child labels? I'll try to fix this if not today (23:53 here) then tomorrow...

**Comment by maxim-zhao** [comment]
I had thought it more likely related to child labels, or perhaps their fully-qualified form, and the value does seem random. No terrible hurry as my workaround seems fine for now.

**Comment by vhelin** [comment]
I hope I got it fixed. At least your and mine (original) test cases work with a FREE .SECTION...

**Comment by vhelin** [comment]
Good question. Perhaps it would be good to make just @InstructionUnderTest to work as well. I'll try to make it work later this week when I have more time...

**Comment by vhelin** [comment]
I hope the commit fixes this issue. If not, let me know here... :)

**Comment by maxim-zhao** [comment]
it seems to work, yes.
