### ISSUE TITLE
In 10.1a, attempting to .DSTRUCT two of the same .STRUCTs results in a WLA-Z80 error `Label "<struct field>" was defined for the second time.`

### ISSUE THREAD

**Issue by SavagePencil** [vhelin/wla-dx#453]
The following code:
```
.STRUCT sState
    OnEnter DW
.ENDST

.DSTRUCT State1 INSTANCEOF sState VALUES:
    OnEnter:  .DW $1234
.ENDST

.DSTRUCT State2 INSTANCEOF sState VALUES:
    OnEnter:  .DW $5678
.ENDST
```

...generates the following error when compiled with `wla-z80` in version 10.1a:  ```INTERNAL_PASS_1: Label "OnEnter" was defined for the second time.```

**Comment by SavagePencil** [comment]
This issue does NOT occur in 10.0.

**Comment by vhelin** [comment]
I'll give this a look at the end of this week - currently I'm too busy with other things...

**Comment by vhelin** [comment]
It seems that your code is broken, you have "VALUES:" there instead of "VALUES". That kinda breaks the assembler which then does silly things and gives a wrong error message.

I'll update the assembler to work better in this situation...

**Comment by SavagePencil** [comment]
Aha!  Note that it does assemble correctly with 10.0.

**Comment by vhelin** [comment]
v10.0 was more tolerant with incorrectly written directives? :) It's interesting why the parser parsed incorrect code and didn't fail...

**Comment by vhelin** [comment]
Ok, v10.1 should now spot such an error in syntax and give a better error message.
