### ISSUE TITLE
Force terminating .endb for every .block

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#46]
WLA doesn't appear to do this, it just stays quiet if you leave one open.

**Comment by vhelin** [comment]
So when should WLA auto terminate the block?

**Comment by cr1901** [comment]
I think the expected/best behavior would be to just error.

**Comment by vhelin** [comment]
Oh yes, at the end of the file?

**Comment by nicklausw** [comment]
Yup.

**Comment by vhelin** [comment]
I took the "give an error" route, as an error was given if a .SECTION wasn't terminated with a .ENDS. Should be fixed in the latest sources.
