### ISSUE TITLE
".countrycode" or ".destinationcode" or so on for wla-gb

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#47]
$14a in a Gameboy rom holds the destination code. It'd be fairly convenient to have a directive to modify it like the rest of the GB header.

In fact, perhaps .gbheader should just become a thing?

**Comment by vhelin** [comment]
.gbheader sounds like a plan as we already have .snesheader. But looking back I wonder why I didn't do .countrycode before... [making some Google searches...]... Oh yes:

  http://bgb.bircd.org/pandocs.htm#thecartridgeheader

e.g., the Pan Docs didn't specify country code for Gameboy ROMs. Only 0x00 - Japanese and 0x01 - non Japanese. Any comprehensive source that lists all these country codes for DMG/GBC?

But codewise this looks like a feature well implemented. :)
