### ISSUE TITLE
__label__ doesn't work in some instances

### ISSUE THREAD

**Issue by aexoden** [vhelin/wla-dx#482]
Given this program:

```
.lorom

.memorymap
	slotsize $8000
        defaultslot 0
        slot 0 $8000
.endme

.rombanksize $8000
.rombanks 16

.bank 0 slot 0

this_is_a_long_label:
        .dw __label__
        .dw __label__ + $2000
```
The second use of ```__label__``` appears to cause issues, giving this error:

```
main.o: main.s:17: PARSE_STACK: Unresolved reference to "this_is_a".
```

I'm not entirely sure, so take this with a grain of salt, but it's at least possible the cause is roughly at line 927 in stack.c, where after calling process_special_labels, the byte at index k is overwritten with a 0, meaning the new label can never be longer than the initial "```__label__```" it read. No idea how to actually fix it, though, since I don't fully understand any of this code.

**Comment by vhelin** [comment]
This doesn't use the stack calculator (and its parsers):

(.dw) __label__

This uses stack calculator and its parsers:

(.dw) __label__ + $2000

Thus the difference, I guess. 

Anyway, good catch, I'll investigate!

**Comment by vhelin** [comment]
Hmm your example seems to work on my laptop, I'll test others...

**Comment by vhelin** [comment]
Works fine elsewhere, but I can see the potential problem in the code, and I think you are correct. What if you now try the latest sources, is the issue gone?

**Comment by vhelin** [comment]
I think I know why the old code worked on my computer, but the behavior can be totally random:

If "__label__" wasn't terminated with 0 process_special_labels() failed, but after coming back from it the string was terminated thus "__label__" was saved for WLALINK which managed to process it correctly?

In the random case "__label__" was somehow terminated with a 0 (the buffer had 0 there in the right place already before "__label__" was put into the buffer?) process_special_labels() succeeded, but after returning from it the string was cut short, if it was longer than 9 characters, and then you got the PARSE_STACK error.

Anyway, if you can confirm that the latest sources work then I can proceed to release v10.1 of WLA DX... :)

**Comment by aexoden** [comment]
It seems to work now. As always, thanks for the quick response.
