### ISSUE TITLE
SECTION attribute to prevent crossing a page boundary

### ISSUE THREAD

**Issue by Kroc** [vhelin/wla-dx#501]
This is kind of like alignment, but the ability to specify that a `SECTION`/`RAMSECTION` must *not* cross an 8-bit boundary.
If a section can be guaranteed not to cross into a 9th bit, then I can make Z80/SM83 code faster by only incrementing an 8-bit counter instead of a 16-bit counter. I just got bitten by this today when code I added bumped a table over a boundary and my code exploded unintentionally!

This is not quite the same as `ALIGN`, as the actual position with the 256-byte range may not be important at all, and even with `ALIGN` you still may not want a section to go over the 8-bit boundary.

I don't really have a suggestion what keyword could be used for this.

**Comment by vhelin** [comment]
Have you checked out WINDOW and BITWINDOW? .SECTION has those and I think they should do the job...

**Comment by Kroc** [comment]
These aren't in the current online documentation and the documentation isn't included in releases either :/

**Comment by vhelin** [comment]
Yes they are in the documentation in v10.1 release. Yes they are here: https://www.villehelin.com/wla-README.html

No, they are not in the Documentation linked in README.md, for some reason. Which is kind an issue... Why https://wla-dx.readthedocs.io/en/latest/ is out-of-date? This needs to be solved...

**Comment by vhelin** [comment]
Ok, Read the Docs can now build the latest documentations.

**Comment by Kroc** [comment]
Ah, `BITWINDOW` is perfect, thanks!
