### ISSUE TITLE
Create a .bat version of run_tests.sh for Windows CMD

### ISSUE THREAD

**Issue by vhelin** [vhelin/wla-dx#505]
Currently the Windows MSVC Azure Pipelines script doesn't run the tests as we don't have a .bat version of the run_tests.sh script...

**Comment by cr1901** [comment]
This in principle should've been 30 minutes for me to add for you, but I've had computer trouble this past week and had to reinstall Windows. I'll see what I can do for getting this done...

**Comment by vhelin** [comment]
Nice! I practically know nothing about .bat scripting...

**Comment by cr1901** [comment]
My opinion after spending a bit of time implementing this is that "you are better off installing `sh`, `make`, `rm`, and friends, and just running `sh run_tests.sh`, even from Windows. This works for me locally, anyway.

**Comment by vhelin** [comment]
Ouch. 

> My opinion after spending a bit of time implementing this is that "you are better off installing sh, make, rm, and friends, and just running sh run_tests.sh, even from Windows. This works for me locally, anyway.

Then the question/issue turns into this: How to install those tools in Azure Pipelines / Windows MSVC script?

**Comment by cr1901** [comment]
Btw, I forgot to ask... is `bsh` (`run_tests.bsh`) on Amiga an older version of `bash` or a different shell? For Amiga OS 3.x or 4.x?

**Comment by vhelin** [comment]
If I interpret bsh.doc correctly, the Amiga bsh I'm using is v0.98. Feels pretty simple and old. Amiga OS 3.1.

![image](https://user-images.githubusercontent.com/6417746/175529748-dc2b62aa-5d20-4ed3-986f-caa98b894b2c.png)

**Comment by vhelin** [comment]
Amiga uses "delete" for remove, but bsh seems to provide "rm". Also running
"bsh run_tests.bsh" on Amiga doesn't error/break in any case so I'll need
to look at the output (for the 15 minutesish it runs) to spot any errors.
Fortunately console's update rate is slow when it scrolls...

Azure Pipelines / Windows could not run run_tests.sh last time I tried,
don't remember what it was missing. Most probably make etc...

**Comment by vhelin** [comment]
I was just messing around the Azure Pipelines .yml files and noticed that when we build Windows exes using Visual Studio solution file we also run the tests (run_tests.sh -windows-x86)..

> Currently the Windows MSVC Azure Pipelines script doesn't run the tests as we don't have a .bat version of the run_tests.sh script...

... so my initial issue didn't actually exist. :D Me and my (bad) chicken memory...
