### ISSUE TITLE
WDM instruction unimplemented

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#510]
Some Super Nintendo developers use `WDM 0` to insert breakpoints, but WLA doesn't understand it:

```
E:\bazz\VRAM-SNES-Program>wla-65816 -o vram.obj vram.asm
vram.asm:90: ERROR: Unknown symbol "WDM".
```

As a workaround, the WDM opcode can be inserted:

`.byte $42, $00`

**Comment by vhelin** [comment]
It's defined in opcodes_65816.c in the official WLA.

![image](https://user-images.githubusercontent.com/6417746/172697259-c24b5920-e9ca-4e60-97a0-d23d755aabef.png)

I just made a test and it assembles correctly (-> $42).  Are you using Bazz's version of WLA DX?

**Comment by vhelin** [comment]
It seems that WDM takes another byte and WLA is currently wrong. I'll fix it...

**Comment by vhelin** [comment]
Ok, do the latest sources fix the issue (they should)?

**Comment by jeffythedragonslayer** [comment]
I came across this bug while following one of bazz's tutorials that is why his name is in my path
