### ISSUE TITLE
Error putting data into two nameless structs

### ISSUE THREAD

**Issue by sverx** [vhelin/wla-dx#513]
It looks like I have just stumbled upon a bug. :thinking: 

It gets triggered when I use `.DSTRUCT ... DATA` with nameless structs.

Here's a fragment of my code:

```
.struct some_struct_definition
  type    db
  some    db
  fields  db
  name    db
  here    db
.endst

.section "some section" free
some_label:
.DSTRUCT instanceof some_struct_definition DATA 1,2,3,4,5
.DSTRUCT instanceof some_struct_definition DATA 6,7,8,9,0
.ends
```

and I get:
`DIRECTIVE_ERROR: "_sizeof_.type" was defined for the second time`
on the second DSTRUCT line.

In the documentation it states that:
> The struct can be defined namelessly, in which case no labels will be generated [...]

but it's instead trying to define the labels I guess.

Of course the error disappears if I give any name to the structs as in

```
.DSTRUCT name_a instanceof some_struct_definition DATA 1,2,3,4,5
.DSTRUCT name_b instanceof some_struct_definition DATA 6,7,8,9,0
```

... but I don't need those names :wink:

**Comment by vhelin** [comment]
I have to admit that I don't remember how it should work, and the
documentation is puzzling to me; if no labels should be generated then that
.DSTRUCT should have no effect and be totally useless?

This is clearly an issue, but how to fix it? Change the documentation?

**Comment by vhelin** [comment]
I searched thorugh closed issues here on GitHub, but couldn't find an answer to how this was initially designed.

I'm kinda hesitant to change the behavior of a feature that's been there for ages even though it doesn't match the documentation. Some people might be using it the way it's been working for years and a change in the behavior would break their code.

I'm thinking about adding keyword NOLABELS to .DSTRUCT so your example would look like this:

```
.section "some section" free
some_label:
.DSTRUCT instanceof some_struct_definition NOLABELS DATA 1,2,3,4,5
.DSTRUCT instanceof some_struct_definition NOLABELS DATA 6,7,8,9,0
.ends
```

How does this sound?

**Comment by sverx** [comment]
If you're worrying for me - don't, as any solution would do, including not even fixing the issue... I will keep on using some meaninglessly random named DSTRUCTS instead of nameless ones and just call it a day :smile: 

As for the issue itself, I agree that fixing it 'properly' might potentially break some existing code and I won't insist on the fix I suggested, even if I believe the only case it worked was when the nameless feature was used only once... if anyone ever tried using two of them they would have get the _"label" defined for the second time_ error for sure.

Still I think nameless DSTRUCTS can be very useful so if to have those we have to pay the price of adding the NOLABELS attribute to them it's a price we can surely accept to pay :smile: 

Thanks!

**Comment by sverx** [comment]
Also issue #276 seems somewhat related, even if it's about UNIONs (check the thread, mostly the second half of it... looks like that's why you added the CL flags for removing the generation of _sizeof_labels )

**Comment by vhelin** [comment]
It seems I've completely ignored the old syntax for .DSTRUCT... I'll fix that today evening. :)

**Comment by sverx** [comment]
The _old syntax_ turned out to be very handy to me because of its compact form, as I can initialize an array of structs using just one line per array element...

I think that form even deserves a better name than _old syntax_  ... maybe the _compact syntax_? The _implicit syntax_?

**Comment by vhelin** [comment]
Does that mean that the docs are wrong? As this works very well:

.DSTRUCT instanceof some_struct_definition NOLABELS DATA 6,7,8,9,0

**Comment by sverx** [comment]
Works perfectly! I didn't know I could even not type the `DATA` keyword at all. Very nice!

Docs doesn't actually imply the nameless structs are not supported in the compact syntax, even if the example is given only for the alternative syntax.

Thanks! :heart: 

Note that of course the error would appear anyway when using two or more nameless `.DSTRUCT`s without NOLABELS explicitly speficified. I suppose this is because of compatibility and it's not a problem.

**Comment by maxim-zhao** [comment]
I think the better fix is to imply NOLABELS if the name is empty.

**Comment by vhelin** [comment]
That might break some old code, but it sounds logical.

**Comment by sverx** [comment]
I thought the point of having `NOLABELS` was exactly to avoid risking to break some old code... did I miss something?

**Comment by vhelin** [comment]
> I thought the point of having `NOLABELS` was exactly to avoid risking to break some old code... did I miss something?

You didn't miss anything, I'm not changing how this works right now. :)
