### ISSUE TITLE
It doesn't like ex hl,de accepts ex de,hl only

### ISSUE THREAD

**Issue by sverx** [vhelin/wla-dx#514]
As the title said, WLA-DX doesn't like me writing `ex hl,de` instead of `ex de,hl`.
Well, maybe the correct form is the latter but I think it could accept also the former, I don't think it would lead to any confusion after all...

**Comment by vhelin** [comment]
Is this WLA-Z80? WLA-GB?

**Comment by sverx** [comment]
WLA-Z80 (sorry!)

**Comment by sverx** [comment]
Confirmed it now gladly accepts `ex hl,de` too.

Thanks! :heart:
