### ISSUE TITLE
Escape sequence for backslash (partially) broken?

### ISSUE THREAD

**Issue by Ramsis-SNES** [vhelin/wla-dx#520]
Putting `\\` at the end (!) of a string like so ...

`.DB "Test\\"`
`.DB "\\"`

... yields an error message, _INPUT_NUMBER: String wasn't terminated properly._

Not sure if this is normal ...? I'm not exactly proficient in C and the likes. :D

**Comment by vhelin** [comment]
You are correct, they should work. I managed to look at the code and it seems that '\\' is not handled anywhere... Fix coming up soon. :) I wonder why this hasn't been spotted before...

**Comment by Ramsis-SNES** [comment]
Super-awesome, thanks, Ville! it works now! :D
