### ISSUE TITLE
.INCBIN "file.bin" READ enhancement

### ISSUE THREAD

**Issue by sverx** [vhelin/wla-dx#531]
I was wondering if it's possible for `.INCBIN` to load only a certain number of bytes from a binary file, but this number is not known beforehand but it's instead based on the size of the binary file itself.
For instance I want to be able to read everything up to the last byte but not load that last one too, say because it is a termination marker I need to skip to juxtapose some other data.

If it's not already possible (I checked the docs and it doesn't seem to be) I think something like using a negative number for the `READ` parameter as in

`.INCBIN "file.bin" READ -1`

would do.

Of course using 

`.INCBIN "file.bin" SKIP 4 READ -1`

should still skip 4 bytes at the beginning of the file and 1 at the end, so it's not simply `READ` _size-1_

**Comment by vhelin** [comment]
Sorry, cannot check the docs right now, will get back to this issue later today evening, but hmm

isn't there .FSIZE?

Use that to get the file's size and then feed the size-1 to .INCBIN?

If not possible, well, I'll get back to this later today... Should be easy to implement such negative sizes...

**Comment by sverx** [comment]
No rush!

BTW it's not just about taking the size and subtracting one anyway...

Thanks!

**Comment by vhelin** [comment]
I hope this commit fixes your issue

**Comment by sverx** [comment]
I'm yet not using this feature, but I think I soon will.
I will report if something will not be working as expected - in the meantime, thank you! :heart:

**Comment by vhelin** [comment]
I think I'll close this issue now as at least my tests pass...

**Comment by sverx** [comment]
> I think I'll close this issue now as at least my tests pass...

Yes, I'll report back in case it won't work as expected. Thanks!
