### ISSUE TITLE
.DESC support for .ENUMID

### ISSUE THREAD

**Issue by Ramsis-SNES** [vhelin/wla-dx#537]
It would be very nice if `.ENUMID` supported `DESC`, just like `.ENUM` does. :-)

**Comment by vhelin** [comment]
I think I'll implement this right away :) Let me grab a beer...

**Comment by vhelin** [comment]
Hmm, a question:

.ENUMID 0 STEP -1

... isn't this like DESC? It should work, by looking at the code...

**Comment by Ramsis-SNES** [comment]
Whoops, indeed, I didn't know this would work, but it does! Thanks yet again! :D
