### ISSUE TITLE
multiple target patterns during make on MINGW32

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#551]
Trying to build wla-dx on MSYS2 MinGW 32-bit.  After successful `cmake .`, hitting this error during `make`:

```
wlab/CMakeFiles/wlab.dir/compiler_depend.make:4: *** multiple target patterns.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1060: wlab/CMakeFiles/wlab.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by vhelin** [comment]
I have to say I don't know much about cmake, someone else modded the project to use it. But when I build WLA DX on Cygwin I need to issue 

  cmake -G "Unix Makefiles"

and then "make" works. Looking at INSTALL file, these are listed:

  cmake -G "Unix Makefiles" .  ; under Unix / OS X / Cygwin / MSYS2
  cmake -G "MSYS Makefiles" .  ; under MSYS / MinGW
  cmake -G "MinGW Makefiles" . ; under (plain) MinGW
  cmake -G "NMake Makefiles" . ; if you wish to use NMake

Would any of those work?
