### ISSUE TITLE
pass -> phase?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#560]
In section 18.1 of the documentation, we have:

> WLA has four separate phases, called a little bit incorrectly passes:

Is there anything stopping us from simply renaming "pass" to "phase" in the source and documentation?  If so, perhaps we elaborate on why pass is bad terminology.

**Comment by vhelin** [comment]
The assembler doesn't really make passes to the source code thus phase is more proper. Or if that doesn't matter then pass works just fine.

**Comment by vhelin** [comment]
I'm not sure if this is really necessary or helpful...

**Comment by vhelin** [comment]
I'm thinking that the 1st and the only pass should remain as pass for clarity so people can easily see that this is a single pass assembler. Docs can also be updated about this.

**Comment by vhelin** [comment]
Nope, just (1st and the only) pass. Maybe. Haven't decided yet. Maybe four phases are fine, I need to think about this some more...
