### ISSUE TITLE
time time typo

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#564]
In doc section 18.1:

> Includes the include files: every **time time** happens the file is read in, white space is removed, lines formatted, etc.

**Comment by vhelin** [comment]
> In doc section 18.1:
> 
> > Includes the include files: every **time time** happens the file is read in, white space is removed, lines formatted, etc.

Yeah, clearly a typo!

**Comment by vhelin** [comment]
> Also I think in section 9 it's a little confusing whether one or two temp files are created, both because "an temporary files" which sounds like a typo and the last sentence which sounds like WLA deletes two files:
> 
> > Note that WLA will generate an temporary files in the current working directory while it works. On Windows and Unix-like systems, the file is called .wla%PID%a, where %PID% is the PID of the process. For other system, it’s just wla_a.tmp.
> > When WLA finishes its work these two files are deleted as they serve of no further use.

That info about tmp file generation is old and wrong, we use ANSI C's tmpfile() on all platforms these days for tmp file generation...

**Comment by vhelin** [comment]
Maybe it's better that I rewrite that section as it might be useful information for the user to know that WLA will generate a tmp file in the current working directory...
