### ISSUE TITLE
Define a way to have sections visible in their file only

### ISSUE THREAD

**Issue by RetroAntho** [vhelin/wla-dx#573]
Hello,

To develop quicker on 65c816, we use (with pvsneslib tool) a C "compiler" which translate c code to wla asm code.
To avoid issues, we have to generate some unique sections or variable names.
As the generated code cannot be managed easily, we use for now a workaround by generating a unique label name with the "tmpnam" function:
```

char sztmpnam[STRING_MAX_SIZE];
strcpy(sztmpnam, &tmpnam(NULL)[1]);
// later in the code
...
fprintf(f, ".RAMSECTION \"ram%s%s\" APPENDTO \"globram.data\"\n", sztmpnam, s->name);
// or 
fprintf(f, ".SECTION \"%s%s\" APPENDTO \"glob.data\"\n", sztmpnam, s->name);
// ...
fprintf(f, "__local_dummy%s%s ", sztmpnam, s->name);
//...
fprintf(f, "\n__local_dummy%s%s: .db 0", sztmpnam, s->name);


```

I guess this is a big change to do and the workaround works great. Do you think it could be interesting for most people to add a new functionality in wla ?
A kind of file-local symbols, the section could be visible in the file where it is created.

**Comment by vhelin** [comment]
Looking at the code it looks like it creates unique labels even inside the same file? 

Anyway, to cut to the chase, this issue requests .SECTIONs to be made somehow local to the file where they were defined in? Would this also make all labels inside such a .SECTION local to the file as well?

**Comment by RetroAntho** [comment]
Yes, it creates unique label/sections in the same file but i guess it is not usefull for label which begin with "__"

In fact, it seems to be related to `glob.data` and `globram.data` which are declared in crt0_snes.asm file :

```
.RAMSECTION "globram.data" BANK $7f SLOT 3 KEEP
.ENDS

.SECTION "glob.data" SUPERFREE KEEP
.ENDS
```

if 2 sections from different source files have the same name, only one is kept ?

As i am not fluent at all with asm, i am not sure that my initial post with "local" items go in the right direction and could solve the case.

If the root cause of my issue is not clear, i can reproduce it (but at the end of week, sorry) without creating the unique label to show the result.

**Comment by vhelin** [comment]
I think I have a hunch of what's going on, but as I cannot work on this either before Saturday / Sunday this week, well, if you can reproduce the issue that'd be great. :) Just to make sure we are on the same page...

**Comment by Kroc** [comment]
> if 2 sections from different source files have the same name, only one is kept ?

1. This should be an error if `APPENDTO` isn't specified (a bug, if WLA DX isn't doing this, no?)
2. Namespaces should be used to have sections share names but not collide, right?

**Comment by vhelin** [comment]
I just checked: WLALINK accepts many .SECTIONs with the same name from different files and keeps them all. So this needs to be turned into an error? Maybe it might be good as if you have two .SECTIONs with the name "ABC" then if you try to APPENDTO "ABC" then you get this:

```
_find_section(): Multiple sections called "Duplicate" found for APPENDTO/AFTER operation. Please have only one section called "Duplicate" in the source files. Using the last found section...
```

Maybe an error here should be better than just a warning...

**Comment by RetroAntho** [comment]
Hi,

Sorry for the late news, i have been busy until yesterday evening...

I prepared a sample but as it require to use pvsneslib, it require to install it to build it.
But with small pieces of code, it should be clear :

Here are 2 .c files :

**a.c :**
```

#include <snes.h>

extern char tilfont, palfont;

char* text1 = "text1";
extern char* text2;

int main(void)
{
    consoleInit();

    consoleSetTextVramBGAdr(0x6800);
    consoleSetTextVramAdr(0x3000);
    consoleSetTextOffset(0x0100);
    consoleInitText(0, 16 * 2, &tilfont, &palfont);

    bgSetGfxPtr(0, 0x2000);
    bgSetMapPtr(0, 0x6800, SC_32x32);

    setMode(BG_MODE1, 0);
    bgSetDisable(1);
    bgSetDisable(2);

    consoleDrawText(10, 8, text1);
    consoleDrawText(10, 10, text2);

    setScreenOn();

    while (1)
    {
        WaitForVBlank();
    }
    return 0;
}


```
**b.c :**
```

char* dmy1 = "0";
char* dmy2 = "0";
char* dmy3 = "0";
char* dmy4 = "0";
char* dmy5 = "0";
char* dmy6 = "0";
char* dmy7 = "0";
char* dmy8 = "0";
char* text2 = "text2";

```

I know the code is bad but i needed workaround to have the same ID automatically generated by tcc tool (which convert .c to .asm)

It produce these .asm files :

**a.c.asm**
```

.include "hdr.asm"
.accu 16
.index 16
.16bit
.define __main_locals 0

.SECTION ".text_0x0" SUPERFREE

main:
.ifgr __main_locals 0
tsa
sec
sbc #__main_locals
tas
.endif
jsr.l consoleInit
pea.w 26624
jsr.l consoleSetTextVramBGAdr
pla
pea.w 12288
jsr.l consoleSetTextVramAdr
pla
pea.w 256
jsr.l consoleSetTextOffset
pla
pea.w :palfont
pea.w palfont + 0
pea.w :tilfont
pea.w tilfont + 0
pea.w (32 * 256 + 0)
sep #$20
rep #$20
jsr.l consoleInitText
tsa
clc
adc #10
tas
pea.w 8192
sep #$20
lda #0
pha
rep #$20
jsr.l bgSetGfxPtr
tsa
clc
adc #3
tas
sep #$20
lda #0
pha
rep #$20
pea.w 26624
sep #$20
lda #0
pha
rep #$20
jsr.l bgSetMapPtr
tsa
clc
adc #4
tas
pea.w (0 * 256 + 1)
sep #$20
rep #$20
jsr.l setMode
pla
sep #$20
lda #1
pha
rep #$20
jsr.l bgSetDisable
tsa
clc
adc #1
tas
sep #$20
lda #2
pha
rep #$20
jsr.l bgSetDisable
tsa
clc
adc #1
tas
lda.l text1 + 0
sta.b tcc__r0
lda.l text1 + 0 + 2
pha
pei (tcc__r0)
pea.w 8
pea.w 10
jsr.l consoleDrawText
tsa
clc
adc #8
tas
lda.l text2 + 0
sta.b tcc__r0
lda.l text2 + 0 + 2
pha
pei (tcc__r0)
pea.w 10
pea.w 10
jsr.l consoleDrawText
tsa
clc
adc #8
tas
jsr.l setScreenOn
__local_0:
jsr.l WaitForVBlank
bra __local_0
lda.w #0
sta.b tcc__r0
__local_1:
.ifgr __main_locals 0
tsa
clc
adc #__main_locals
tas
.endif
rtl
.ENDS
.RAMSECTION "ram.data" APPENDTO "globram.data"

text1 dsb 4

.ENDS

.SECTION ".data" APPENDTO "glob.data"

.dw tccs_L.8 + 0, :tccs_L.8
.ENDS

.SECTION ".rodata" SUPERFREE

tccs_L.8: .db $74,$65,$78,$74,$31,$0
.ENDS

.RAMSECTION ".bss" BANK $7e SLOT 2
__local_dummybss dsb 1
.ENDS

```

**b.c.asm**
```

.include "hdr.asm"
.accu 16
.index 16
.16bit
.RAMSECTION "ram.data" APPENDTO "globram.data"

dmy1 dsb 4
dmy2 dsb 4
dmy3 dsb 4
dmy4 dsb 4
dmy5 dsb 4
dmy6 dsb 4
dmy7 dsb 4
dmy8 dsb 4
text2 dsb 4

.ENDS

.SECTION ".data" APPENDTO "glob.data"

.dw tccs_L.0 + 0, :tccs_L.0
.dw tccs_L.1 + 0, :tccs_L.1
.dw tccs_L.2 + 0, :tccs_L.2
.dw tccs_L.3 + 0, :tccs_L.3
.dw tccs_L.4 + 0, :tccs_L.4
.dw tccs_L.5 + 0, :tccs_L.5
.dw tccs_L.6 + 0, :tccs_L.6
.dw tccs_L.7 + 0, :tccs_L.7
.dw tccs_L.8 + 0, :tccs_L.8
.ENDS

.SECTION ".rodata" SUPERFREE

tccs_L.0: .db $30,$0
tccs_L.1: .db $30,$0
tccs_L.2: .db $30,$0
tccs_L.3: .db $30,$0
tccs_L.4: .db $30,$0
tccs_L.5: .db $30,$0
tccs_L.6: .db $30,$0
tccs_L.7: .db $30,$0
tccs_L.8: .db $74,$65,$78,$74,$32,$0
.ENDS

.RAMSECTION ".bss" BANK $7e SLOT 2
__local_dummybss dsb 1
.ENDS
```


We can see that the .SECTION ".rodata" have both tccs_L.8 so the code build correctly but i finally have the text "text2" which appears twice instead of "text1" and "text2":

![Capture d’écran du 2023-05-07 17-01-41](https://user-images.githubusercontent.com/48180545/236686689-fb544fd3-f745-4d13-9124-6c4352087af4.png)



Thanks for the code improvement you did, i agree with you and i think that it is better to produce an error instead of a warning.

I also saw that you added the -a flag (then updated to ISOLATED keyword) so i guess that i have to define it at each beginning of file to avoid generating unique ID everywhere ?


I have to do some tests, i keep you informed as soon as possible :)

**Comment by vhelin** [comment]
ISOLATED is actually a parameter for .INCLUDE so you cannot issue .ISOLATED at the moment.

I could add something like

  .NAMESPACE "MyNamespace"

so everything that follows in that file gets put into a namespace, which would work like ISOLATED for .INCLUDE, but I'm not sure if that should be done...

**Comment by vhelin** [comment]
Looking at the generated code it's quite clear that we should allow .SECTIONs with the same name...

**Comment by RetroAntho** [comment]
I am not enough fluent with asm to have an opinion on it.
But i see that it works with the same name but produce side effects (as in the sample).
That is why we generated a unique label for each file, but i find this solution is bad.
2 executions of the same file does not produce the same output. For example, if you want to compare 2 files, you will have a lot of differences related to the unique ID

**Comment by vhelin** [comment]
If I understand this correctly the problem might be with tccs_L.8 - there are two of them, one in a.c.asm and one in b.c.asm. WLALINK doesn't seem to detect duplicate labels so I guess, when fixing references, it'll use the one it'll find first.

I guess I could add duplicate label detection to WLALINK, and you, to fix your problem (if that's the reason), you could add unique prefixes (the filename?) to those labels in ".data" and ".rodata".

**Comment by vhelin** [comment]
WLALINK accepts duplicate labels, but then you'll get this

main.o: exmain.s:131: TRY_PUT_LABEL: Label "duplicatelabel" was defined more than once.

... which is also a warning. I think I'll turn this into an error as giving here just a warning the user might not see the warning and think that everything is ok, but in fact it's not... ?

**Comment by vhelin** [comment]
If seems it gave an error at one point, but it was turned into a warning. No idea why...

![kuva](https://user-images.githubusercontent.com/6417746/236689220-99a84e0e-41a1-43cb-ab33-666dc8240125.png)

**Comment by vhelin** [comment]
@RetroAntho When you assemble your project, can you see such a warning about tccs_L.8?

**Comment by RetroAntho** [comment]
Yes in this sample, tccs_L.8 is the source of the issue.

I confirm that the warning appears :
`src/b.obj: src/b.asm:36: TRY_PUT_LABEL: Label "tccs_L.8" was defined more than once.`

but with this small sample (which use the pvsneslib library which contains a lot of code), we already have more than 100 lines of output like :

```
/mnt/Repository/pvsneslib/devkitsnes/bin/wlalink -d -s -v -A -L /mnt/Repository/pvsneslib/pvsneslib/lib linkfile hello_world.sfc
src/b.obj: src/b.asm:27: TRY_PUT_LABEL: Label "SECTIONSTART_.rodata" was defined more than once.
src/b.obj: src/b.asm:36: TRY_PUT_LABEL: Label "tccs_L.8" was defined more than once.
src/b.obj: src/b.asm:37: TRY_PUT_LABEL: Label "SECTIONEND_.rodata" was defined more than once.
src/b.obj: src/b.asm:40: TRY_PUT_LABEL: Label "SECTIONSTART_.bss" was defined more than once.
src/b.obj: src/b.asm:42: TRY_PUT_LABEL: Label "SECTIONEND_.bss" was defined more than once.
/mnt/Repository/pvsneslib/pvsneslib/lib/libc.obj: libc_c.asm:27: TRY_PUT_LABEL: Label "SECTIONSTART_.text_0x0" was defined more than once.
/mnt/Repository/pvsneslib/pvsneslib/lib/libc.obj: libc_c.asm:90: TRY_PUT_LABEL: Label "SECTIONEND_.text_0x0" was defined more than once.
/mnt/Repository/pvsneslib/pvsneslib/lib/libc.obj: libc_c.asm:7285: TRY_PUT_LABEL: Label "SECTIONSTART_.rodata" was defined more than once.
/mnt/Repository/pvsneslib/pvsneslib/lib/libc.obj: libc_c.asm:7287: TRY_PUT_LABEL: Label "SECTIONEND_.rodata" was defined more than once.
/mnt/Repository/pvsneslib/pvsneslib/lib/libc.obj: libc_c.asm:7290: TRY_PUT_LABEL: Label "SECTIONSTART_.bss" was defined more than once.
/mnt/Repository/pvsneslib/pvsneslib/lib/libc.obj: libc_c.asm:7292: TRY_PUT_LABEL: Label "SECTIONEND_.bss" was defined more than once.
DISCARD: /mnt/Repository/pvsneslib/pvsneslib/lib/libm.obj: libm.asm: Section ".fp_libm" was discarded.
DISCARD: /mnt/Repository/pvsneslib/pvsneslib/lib/libc.obj: maps.asm: Section ".reg_maps7e" was discarded.
DISCARD: /mnt/Repository/pvsneslib/pvsneslib/lib/libc.obj: sm_spc.asm: Section ".sm_spc" was discarded.
...
```

Some warnings can probably be ignored as it could be the right behaviour, and not some others. I have some troubles to differentiate it.

The issue is fixed from our side by generating a unique label as you mentionned. It was done initially with the `tmpnam` function but it produce some issues on Windows with MSYS2 and UCRT64, so it is now this function :
```
void generate_token(char *str, size_t max_size)
{
    size_t i;
    int seed;

    // Generate a unique seed based on the current time
    seed = (unsigned int)time(NULL);
    srand(seed);

    // Generate random mixed case letters
    for (i = 0; i < max_size; i++) {
        if (rand() % 2 == 0) {
            str[i] = 'a' + (rand() % 26);
        } else {
            str[i] = 'A' + (rand() % 26);
        }
    }

    // Null-terminate the string
    str[max_size] = '\0';
}
```

But i am still convinced that it could be more readable in the asm code without this unique ID if i have an other way to have the same result. I have to find a better way to do it. Maybe by using a namespace on each file ?

**Comment by vhelin** [comment]
Ok that is a lot of output. I made WLALINK now to give an error with duplicate labels by default, but if you still need to allow that you can use -c. 

Instead of making the whole label totally random you could add a random postfix to labels like tccs_L.8 to keep them still somewhat readable. Like

tccs_L.8.A23426348

Currently there is no simple way to make WLA handle your case. Or at least I don't see one. This is the critical block:

```

.SECTION ".data" APPENDTO "glob.data"

.dw tccs_L.0 + 0, :tccs_L.0
.dw tccs_L.1 + 0, :tccs_L.1
.dw tccs_L.2 + 0, :tccs_L.2
.dw tccs_L.3 + 0, :tccs_L.3
.dw tccs_L.4 + 0, :tccs_L.4
.dw tccs_L.5 + 0, :tccs_L.5
.dw tccs_L.6 + 0, :tccs_L.6
.dw tccs_L.7 + 0, :tccs_L.7
.dw tccs_L.8 + 0, :tccs_L.8
.ENDS

.SECTION ".rodata" SUPERFREE

tccs_L.0: .db $30,$0
tccs_L.1: .db $30,$0
tccs_L.2: .db $30,$0
tccs_L.3: .db $30,$0
tccs_L.4: .db $30,$0
tccs_L.5: .db $30,$0
tccs_L.6: .db $30,$0
tccs_L.7: .db $30,$0
tccs_L.8: .db $74,$65,$78,$74,$32,$0
.ENDS

```

The tccs_L.* labels defined inside this file should be globally unique. Or made somehow local labels. Currently local labels are contained inside one single .SECTION so we cannot use them here.

Perhaps be could use substitution here?

```

.SECTION ".data" APPENDTO "glob.data"
.dw tccs_L_{UNIQUEID}.8 + 0, :tccs_L.8
.ENDS

.SECTION ".rodata" SUPERFREE
tccs_L_{UNIQUEID}.8: .db $74,$65,$78,$74,$32,$0
.ENDS

```

Then you needed to generate a .DEFINE before those .SECTIONs, like

.DEFINE UNIQUEID 526453284

But still it would be your compiler's job to keep that UNIQUEID globally unique.

**Comment by vhelin** [comment]
Hmm, if all generated asm files have unique names then you could try this:

```

.SECTION ".data" APPENDTO "glob.data"
.dw tccs_L_{WLA_FILENAME}.8 + 0, :tccs_L.8
.ENDS

.SECTION ".rodata" SUPERFREE
tccs_L_{WLA_FILENAME}.8: .db $74,$65,$78,$74,$32,$0
.ENDS

```

???

**Comment by vhelin** [comment]
Also, be warned about your generate_token(): As you seed the random generator inside the function, all calls during the same second give the same output. Or I think that's what it does. Better put this block into the main() of the application:

```

seed = (unsigned int)time(NULL);
srand(seed);

```

**Comment by RetroAntho** [comment]
Thanks for details.
I just tried the last version of wla and i confirm that the build process return now an error because of duplicated sections.

As this part will require more changes in our code, it was a good idea to create the "-c" flag to disable it !
For now, i am using it and the goal will be to remove this flag ASAP !

I just tried the {WLA_FILENAME}, it works correctly for my sample and solve the case without defining the unique ID.

On the previous sample (with "text1" and "text2"), the .rodata become :
```
.SECTION ".rodata" SUPERFREE

tccs_L.{WLA_FILENAME}0: .db $30,$0
tccs_L.{WLA_FILENAME}1: .db $30,$0
tccs_L.{WLA_FILENAME}2: .db $30,$0
tccs_L.{WLA_FILENAME}3: .db $30,$0
tccs_L.{WLA_FILENAME}4: .db $30,$0
tccs_L.{WLA_FILENAME}5: .db $30,$0
tccs_L.{WLA_FILENAME}6: .db $30,$0
tccs_L.{WLA_FILENAME}7: .db $30,$0
tccs_L.{WLA_FILENAME}8: .db $74,$65,$78,$74,$32,$0
.ENDS
```

You mentioned: "if all generated asm files have unique names" and i checked the .sym file generated at the end.

```
0000ba10 SECTIONSTART_.rodata
0000ba10 tccs_L.src/a.asm8
0000ba16 SECTIONEND_.rodata
007f0000 dmy1
007f0004 dmy2
007f0008 dmy3
007f000c dmy4
007f0010 dmy5
007f0014 dmy6
007f0018 dmy7
007f001c dmy8
007f0020 text2
0000b9f3 SECTIONSTART_.rodata
0000b9f3 tccs_L.src/b.asm0
0000b9f5 tccs_L.src/b.asm1
0000b9f7 tccs_L.src/b.asm2
0000b9f9 tccs_L.src/b.asm3
0000b9fb tccs_L.src/b.asm4
0000b9fd tccs_L.src/b.asm5
0000b9ff tccs_L.src/b.asm6
0000ba01 tccs_L.src/b.asm7
0000ba03 tccs_L.src/b.asm8
0000ba09 SECTIONEND_.rodata
```
The {WLA_FILENAME} variable seems to embbed the folder so i guess we will not have issues related same file names in different folders.

I hope the "/" will not produce issues on Windows. I remember that in the 1st version we used, our unique file name contained "/" and did not worked on Windows (we replaced it by an other character).

This solution seems the good one :)
I have to do other tests on taller sample. I keep you informed of the result

**Comment by vhelin** [comment]
I'm curious about this one, did you manage to get everything to work well?

**Comment by RetroAntho** [comment]
No, it is still not fully functional and we gather multiple issues that we have difficulties to solve.
As everything is ready and implemented from WLA side, i guess we can close the issue as i do not know if we will need some weeks or months to solve our cases.

While we have this issue opened, i take advantage for another question (and will open a new issue depending your responses).
Does WLA can override header informations in the 1st bank if this one is full ? (I mean, does the 1st bank should have less than 32k of data as it include th header ?).
Someone pointing an issue with the snes header which have some values override but i am more convinced that it is still related to the translation from C to ASM than something in WLA.

**Comment by vhelin** [comment]
> Does WLA can override header informations in the 1st bank if this one is full ? (I mean, does the 1st bank should have less than 32k of data as it include th header ?).
Someone pointing an issue with the snes header which have some values override but i am more convinced that it is still related to the translation from C to ASM than something in WLA.

If the 1st bank is 32KBs and WLA is instructed to write SNES header (LoROM?) then it takes some space from that ROM bank. The assembler writes and thus reserves the header bytes, but I think it should be possible to overwrite those with your own code ("OVERWRITE" .SECTIONs). Then if checksum is requested, WLALINK will write those at the very end of linking, just before the ROM file is written out.

Does this answer your question?
