### ISSUE TITLE
Macro ARGS Issue #2 -- cannot request bank of named argument

### ISSUE THREAD

**Issue by bazzinotti** [vhelin/wla-dx#58]
http://botb.club/~bazz/wladx/issue58.zip

This problem occurs when passing a label to the macro as a named argument
```
FIX_REFERENCES: Bank number request for an unknown label "label".
```
```
.macro UP_VRAM_ADDR ARGS label
    lda #:label ;LABEL
.endm
```

temporary fix:
```
.macro UP_VRAM_ADDR ARGS label
    lda #:\1 ;LABEL
.endm
```

**Comment by bazzinotti** [comment]
I did a lot of editing to the post, so if you're reading email -- please see the github website URL for latest version.

**Comment by bazzinotti** [comment]
corrected the code

**Comment by bazzinotti** [comment]
bug_exhibition :) http://botb.club/~bazz/wladx/issue58.zip

**Comment by bazzinotti** [comment]
Hey, issue #58 (this issue) and #59 both stem from an inability to access the bank byte. Is there a relationship?

**Comment by vhelin** [comment]
If you give names to macro arguments, they are going to be... tadah - internally definitions! :) \1 is parsed differently...

Why I didn't create definitions called \1 etc - I do not kwow. That would be simpler... Well, I'll add this to my do-when-refactoring list. :) Live and learn.

Anyway, I'll look into this issue.

**Comment by vhelin** [comment]
In the end I went and rewrote the macro argument expansion function, and it should be pretty sweet now. :) I even had labels like "\1_\2:" in my old examples projects that were failing... I had no memory of supporting such usage of macro arguments, especially having macros calling macros, but all that should work now.

If you could test this, thanks! :)

**Comment by bazzinotti** [comment]
I can't do this right now, but I'll do it after I take care of some very important things.

**Comment by bazzinotti** [comment]
I will be going offline for the next few days up to a week. I did not get the chance to test this.

**Comment by nicklausw** [comment]
I can test it later today.

**Comment by vhelin** [comment]
Cool, no hurry guys! I can also try to test it more later today, if I have
time... I'll start working in a new job next Monday, so after that my time
will be pretty limited, at least for a month or two until I get everything
rolling...

**Comment by vhelin** [comment]
Anyone tested the fix to this?

**Comment by bazzinotti** [comment]
Hi Ville, I'm getting a new job so I'm pretty busy. But I've been thinking to myself -- how can we reliably test without a testing framework?? There's no real way to see if previous functionality is being broken in any way, right? If that's the case, we really ought to bang out test cases before being able to implement new features reliably. Am I right?

**Comment by cr1901** [comment]
cmake provides ctest. I had meant to port all the examples to use test (or be usable from Makefiles alone), but for the time being my contributions to WLA are limited thanks to real life problems. I'll pull the code when I can and add prelim ctest support.

**Comment by nicklausw** [comment]
...Aw crap, I meant to test this two months ago. Will do if I can remember (on a school computer at the moment, so wla's not handy, obviously).

**Comment by vhelin** [comment]
I tested this one again today, using the latest sources, and seemed to work, so I'll close this issue 58.
