### ISSUE TITLE
wla-spc700.exe appears to have succeeded when given non-existent input file

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#582]
`wla-spc700.exe` doesn't complain if you give it a source file that doesn't exist as input, creating the impression that the assembling succeeded when it actually didn't.  This can be a big deal if a build script is calling `wla-spc700.exe` because the build script ends up lying to you that the build succeeded, and then you end up running the old ROM from the last build, and then are surprised that new code you added isn't being assembled.

In fact, `wla-spc700.exe` doesn't tell you anything at all when you run it with no args.

**Comment by vhelin** [comment]
Ok, this sounded interesting. I wonder what was wrong and does it happen to anybody else...
