### ISSUE TITLE
Documentation for MVP/MVN

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#583]
In the SNES scene, the instructions `MVP` and `MVN` have a reputation for having different syntaxes in different assemblers, but the WLA-DX documentation doesn't say what the syntax is, so people have to guess.

**Comment by vhelin** [comment]
Looking at i65816.c WLA DX supports these syntaxes:

![kuva](https://github.com/vhelin/wla-dx/assets/6417746/034e64c2-c4ff-4f4e-95d0-a2e52948cf4b)

Please let me know if there are any other syntaxes, perhaps I could support them all.

**Comment by vhelin** [comment]
About different ways of writing MVN/MVP, I found this: https://ersanio.gitbook.io/assembly-for-the-snes/collection-of-values/moves

![kuva](https://github.com/vhelin/wla-dx/assets/6417746/8b974f01-7564-4b70-a10e-b67aa86665e8)
![kuva](https://github.com/vhelin/wla-dx/assets/6417746/901dd341-2493-43c8-8128-7d1b7642241c)

I'm thinking about adding support for format "MVP $xxyy" as well. I'll also add them to the documentation...

**Comment by vhelin** [comment]
> Well, I mean I think it should be explained here:
> 
> https://wla-dx.readthedocs.io/en/latest/#id2

Actually section 15.5 is a better place for the documentation

**Comment by vhelin** [comment]
Same here

![kuva](https://github.com/vhelin/wla-dx/assets/6417746/5db8284d-87ad-4edb-adf3-0013e5c30f90)

... as we don't have that file...

**Comment by vhelin** [comment]
> When I click the 15.5 link, it takes me to 3.3

Found a way to fix that
