### ISSUE TITLE
65c816's PLB unsupported?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#592]
WLA appears to not support this instruction:

https://sneslab.net/wiki/PLB

When I tried assembling the file attached here:

https://forums.atariage.com/topic/351255-the-completely-underappreciated-possibilities-of-mode-0-on-snes/page/9/#comment-5286540

I got this error from wla-65816.exe:

`mode0.s:31: ERROR: Cannot process "plb". Syntax error?`

**Comment by vhelin** [comment]
WLA supports PLB, just tried it out, it's listed in i65816.c:

![image](https://github.com/vhelin/wla-dx/assets/6417746/05aef9af-ede0-4d49-a113-18a30f55fcd5)

Maybe that error comes from something else? Could you show the context of PLB in your code? You've done make clean + make?

**Comment by cr1901** [comment]
I suspect there may be a bug in the rebuild logic. Does this error go away after a clean build?

**Comment by vhelin** [comment]
If you had's updated the source files for time time, pulled the latest sources and issued just "make" without "make clean", then it could be broken state as I've updated i65816.c quite recently, added a couple of new instructions there. It seems that the makefiles/cmake files don't make a clean build (the instruction LUTs need to be rebuilt after such)...

![image](https://github.com/vhelin/wla-dx/assets/6417746/f9ac177c-432c-4bdf-b959-919f8058878c)

So this phase is critical after changing i*.c

![image](https://github.com/vhelin/wla-dx/assets/6417746/6f4fd8c9-2d0b-4356-b083-d3193d636087)

I think that 

![image](https://github.com/vhelin/wla-dx/assets/6417746/ce5ad4be-24b3-451d-a914-c6bee549df7d)

is another issue...

**Comment by vhelin** [comment]
I don't know what you are going to achieve with that, but I guess this should work:

```
BGCityBridge:
	phb				;\
	phk
	plb		;/	Switch data bank.
```

**Comment by vhelin** [comment]
> I don't know what you are trying to achieve with that, but I guess (without knowing what that phk : means) this should work:
> 
> ```
> BGCityBridge:
> 	phb				;\
> 	phk
> 	plb		;/	Switch data bank.
> ```

**Comment by vhelin** [comment]
I'm guessing that you are trying to assemble code written for some other assembler than WLA DX so it's going to need modifications to go through WLA DX:..

**Comment by vhelin** [comment]
That would be helpful, but not totally sure how to implement such logic. And what puzzles me is that loose ':' doesn't give an error as it should. I'm going to try to find out why...

**Comment by vhelin** [comment]
The interesting thing here is that if I give WLA-65816

```
phk : plb
```

... I get this

![image](https://github.com/vhelin/wla-dx/assets/6417746/dbae8a1b-85de-45ed-8715-9abf1944f074)

The parser cannot find an instruction "phk :" and I think that's a proper error in that case. 

I just added a feature where you can put multiple instructions on the same line when separated with " \ " so I'm kinda thinking you should use that here. Still not sure what "phk : plb" means, really, but I guess it's the same as "phk \ plb".

**Comment by vhelin** [comment]
Well, it's been a couple of decades since I last did anything with BASIC so I have to say that I don't remember... To be sure, better read Asar's documentation.
