### ISSUE TITLE
wla-spc700.exe assembles nonsensical mmenomincs

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#596]
So I have blah.s, which I have typed the nonsensical mnemonic "blah" into:

```
.ROMBANKSIZE 100
.ROMBANKS 8

BLAH
```

and then when I do this:

`$ wla-spc700.exe blah.s`

A blah.o file is produced with no errors.  Therefore it's hard to trust the assembler if it will accept pretty much anything.

**Comment by vhelin** [comment]
If BLAH is at the beginning of a line then it's interpreted as a label

**Comment by vhelin** [comment]
> > Labels are ordinary strings (which can also end to a :)
> 
> I think it should say "can also end with a"

Thanks, just fixed this

**Comment by vhelin** [comment]
> How do you feel about adding a directive to disallow labels that don't end in colons? If I mistype a mnemonic, I want the assembler to warn me instead of silently not emitting any machine code for it.

Well, if you write code so that it's not at the beginning of the line then you should not have such problems. :) But if you feel that you need such commandline option then feel free to open a new issue about it, I can do it.
