### ISSUE TITLE
[Feature Request] directive to require label names to end in a colon

### ISSUE THREAD

**Issue by jeffythedragonslayer** [vhelin/wla-dx#598]
Some people do not like assemblers that turn typo'd mnemonics into labels because it means it takes longer to catch mistakes.  It would be nice if there was a directive that tells WLA to emit an error if it sees something on a line that isn't a mnemonic nor a label name ending in a colon.

**Comment by vhelin** [comment]
Directive's not really the way to go here so I added a commandline switch.

**Comment by vhelin** [comment]
Why not? :) Better ideas?

**Comment by vhelin** [comment]
You mean "-With"?
