### ISSUE TITLE
Executeables not actually working on XP with PIII

### ISSUE THREAD

**Issue by Kroc** [vhelin/wla-dx#631]
I have a Pentium III sub-notebook I'd like to use to do some CP/M coding. My project [v80](https://github.com/Kroc/v80) uses WLA-DX to bootstrap a Z80 assembler in Z80. Using the 10.6 release the binaries crash with an access violation.

Knowing that the Pentium III doesn't have SSE2 -- I already had to change the VS solution for [RunCPM](https://github.com/MockbaTheBorg/RunCPM) -- I changed the v10.6-tag 32-bit release build to use NO vector extensions, not even SSE1 and recompiled but even this doesn't work.

![image](https://github.com/vhelin/wla-dx/assets/142650/fafc799b-cddc-4b9b-8632-04fb8d37adb8)

Do you have any means to test a real WindowsXP machine, maybe one without SSE2?  
I'll try get you some more details once I'm back home with the Pentium III laptop.

**Comment by vhelin** [comment]
Unfortunately I don't have any such old computers with Windows XP. :( Even my parents' retired old computer is too new... I think the SDK we use to build WLA DX should allow the executables to run under Windows XP, but yeah, haven't tested that. I guess, like you say, now it's up to get the settings correct for old CPUs...

If you can do that, please let us have the modified Visual Studio solution!

**Comment by Kroc** [comment]
I'll tinker with it and see what I can do!

**Comment by Kroc** [comment]
Okay, I got it working, I didn't realise I was applying changes to only one project and not every project -- Visual Studio's solution management is pure awful.

![it-lives](https://github.com/vhelin/wla-dx/assets/142650/55ded220-4bd8-4e33-8c18-97302a98d574)

**Comment by vhelin** [comment]
Oh yeah, please let us know what you did and make a pull request out of the solution file if you think it's something that would work for everybody. I don't think we need SSE2 etc. flags in master... :)

**Comment by vhelin** [comment]
Well, I did the same to x86/Win32 in the Visual Studio projects

![image](https://github.com/vhelin/wla-dx/assets/6417746/72385623-d956-42dd-a5d0-074276d52f75)

I hope that's enough. I assume we can close this issue.

**Comment by Kroc** [comment]
I've been very busy and not at the place where my PIII laptop is but I will test once I get there.
I would recommend changing compiler optimisation to favour size over speed for x86 so that the code doesn't blow out the cache on old CPUs making them run much slower. A crappy modern CPU might have 128KB of L1 cache but that's the entire L2 cache of a PIII and its L1 is only 8KB!

**Comment by vhelin** [comment]
Done!
