### ISSUE TITLE
wla-68000: BCLR, BSET, BTST: wrong range for immediate bit number parameter

### ISSUE THREAD

**Issue by sircodalotkob** [vhelin/wla-dx#644]
The command
```
btst #$00,(a0)
```
results in `INPUT_NUMBER: The value 0 is out of range [1, 8].`

But bit numbers are zero-based. The range of valid bit number should be [0, 7].

**Comment by vhelin** [comment]
If you think, with the latest sources, that the issue is now fixed (tests worked), please close this issue as well. :)

**Comment by sircodalotkob** [comment]
Worked here as well.
