### ISSUE TITLE
wla-68000: SP not recognized as an alias of A7

### ISSUE THREAD

**Issue by sircodalotkob** [vhelin/wla-dx#645]
On the 68000, the address register `a7` is used as the stack pointer. Many assemblers allow writing `sp` instead of `a7`.
```
movem d0-d7,-(sp)
```
is equivalent to
```
movem d0-d7,-(a7)
```
Adding an option to enable `sp` as an alias for `a7` could help wla-68000 understand more existing code.

**Comment by vhelin** [comment]
Thanks for these two reports! I'll try to fix them later this week...

**Comment by vhelin** [comment]
If the latest sources fix this issue (at least my tests passed), please close this issue. :)

**Comment by sircodalotkob** [comment]
Looks good so far.
