### ISSUE TITLE
INCDIR INCBIN cache bug

### ISSUE THREAD

**Issue by galaxyhaxz** [vhelin/wla-dx#65]
WLA caches files when used in INCBIN. This isn't a problem when using the following code:
DATA1: .INCBIN "world_1/level1.bin"
DATA2: .INCBIN "world_2/level1.bin"

However, if we use INCDIR to shorten this:
.INCDIR "world_1"
DATA1: .INCBIN "level1.bin"
.INCDIR "world_2"
DATA2: .INCBIN "level1.bin"

Will result in DATA2 being overwritten by DATA1, because of the same file name. I think this could be fixed by making WLA append the current INCDIR to the file name so that the whole file name will be used just like in the first example. I have been disassembling Super Mario World into a source code and I have noticed this is a frequent issue when using .INCBIN on many files. Hope this can be fixed.

**Comment by vhelin** [comment]
On Tue, Oct 20, 2015 at 10:53 AM, galaxyhaxz <notifications@github.com>
wrote:

> WLA caches files when used in INCBIN. This isn't a problem when using the
> following code:
> DATA1: .INCBIN "world_1/level1.bin"
> DATA2: .INCBIN "world_2/level1.bin"
>
> However, if we use INCDIR to shorten this:
> .INCDIR "world_1"
> DATA1: .INCBIN "level1.bin"
> .INCDIR "world_2"
> DATA2: .INCBIN "level1.bin"
>
> Will result in DATA2 being overwritten by DATA1, because of the same file
> name. I think this could be fixed by making WLA append the current INCDIR
> to the file name so that the whole file name will be used just like in the
> first example. I have been disassembling Super Mario World into a source
> code and I have noticed this is a frequent issue when using .INCBIN on many
> files. Hope this can be fixed.
>

Oops, what a silly bug. :) Thanks for the report, I'll try to fix it asap
(at the end of this week, perhaps)...

**Comment by vhelin** [comment]
Hey, can you verify that the latest commit fixes this bug? :) I added a testcase for it that I used to check manually that the bug was fixed, but the more testing (especially by not the author of the bugfix) the better.

**Comment by galaxyhaxz** [comment]
I tested with the latest build and it indeed worked. Thanks for the fix.

**Comment by vhelin** [comment]
No prob! That bug has been there for years, LOL. :)
