### ISSUE TITLE
enhancement: have function-style defines

### ISSUE THREAD

**Issue by sverx** [vhelin/wla-dx#7]
Hi!
  would it be possible to expand ".DEFINE" functionality to include function-style defines?
What I'd like to do for instance is something like that:

```
.define Make_Addr(addr)     ((addr>>10)|%11110001)      ; builds the value from the address
```

so that I can use it for instance with constants like in

```
.db Make_Addr($2000), Make_Addr($2200)
```

Thanks!

**Comment by cr1901** [comment]
Ville: I've been reading SICP a bit, so forgive me for this suggestion. Is it possible to make macros and the various directives return values? For example:

```
.MACRO SQUARE X
X * X ;This returns the square of X, to be used in another expression.
.ENDM
```

**Comment by vhelin** [comment]
Hmm, after all these years I have to say that .MACROs are the suggested way of doing such things. Implementing such function like defines are just about doing the same thing in a different way. And .MACROs can also "return" values: just make them use a .DEFINE to contain the return value and use that after the .MACRO call... It's a bit clunky, but it should work just fine.

Function like .DEFINEs are a nice idea, but I'm not sure anyone here has the time to implement such things. :)

**Comment by vhelin** [comment]
See https://github.com/vhelin/wla-dx/issues/309 for ideas about how to implement this feature

**Comment by sverx** [comment]
Has this feature been added? :astonished:

**Comment by vhelin** [comment]
> Has this feature been added? 😲

Yeah, took me only 8 years :)

**Comment by vhelin** [comment]
All feedback is welcome! And the more you can test this new feature the better. :)

The only issue with it, I know, is that string substitutions are executed when the .FUNCTION body is parsed, not when the .FUNCTION is called. It prevents the user from using .FUNCTION arguments in string substitutions inside the .FUNCTION body...

Fixing that is something that I currently see as a big can of worms. It doesn't mean that there is an easy way to do it, I just cannot see one at the moment...

**Comment by sverx** [comment]
> The only issue with it, I know, is that string substitutions are executed when the .FUNCTION body is parsed, not when the .FUNCTION is called. It prevents the user from using .FUNCTION arguments in string substitutions inside the .FUNCTION body...

I don't think I get what you mean here. Can you give me an example?

**Comment by vhelin** [comment]
.function getData(var1) DATA_ITEM{%.2d{var1}}

if var1 isn't defined as a define when WLA parses this it'll give you an error.

If var1 is let's say

.DEFINE var1 = 1

then this .FUNCTION body will become DATA_ITEM_01 and the function will return the value of DATA_ITEM_01 regardless of what you give getData()...

**Comment by sverx** [comment]
Ouch!

But if it works correctly when performing math it's a keeper.

**Comment by vhelin** [comment]
I'm closing this issue as all my .FUNCTION (and .FUNCTION call) tests work, which means the issue should be fixed. But yeah, the substitution problem remains, but I'm thinking that it's a minor thing - substitution in general might not be a very commonly used feature. 

If the current implementation of .FUNCTION is not enough, please open a new issue.
