### ISSUE TITLE
Question: pass_1.c, strcmp and strcaselesscmp

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#76]
I noticed that some directives are compared with strcmp, and others with strcaselesscmp. Why are two different functions used when in the end, they seem to do the same thing?

**Comment by vhelin** [comment]
I guess sometimes some things are done better than usually - would the caseless compare work better in fact? I don't know, can't take a look at the moment, but if you have the energy, please check it out and suggest a fix. :)

**Comment by vhelin** [comment]
Sorry, pressed the wrong button...

**Comment by mckaygerhard** [comment]
this makes ambigous the compares.. i dont think so!
