### ISSUE TITLE
Increase per-file section count limit

### ISSUE THREAD

**Issue by maxim-zhao** [vhelin/wla-dx#8]
I've run into the 255 section limit, and had a failed attempt at increasing it myself...

This would be a breaking change to the object format (as section numbers are a byte), plus the linker makes some assumptions about it too.

My approach was to try to define a limit in defines.h and emit IDs as 4-byte numbers in the object file.

My use case is using a macro to emit "overwrite" sections overlaying an .incbin-ed binary. The alternative is to just overwrite, but of course that produces scary warnings.

**Comment by pinobatch** [comment]
> Temporary solution: Without fully understanding the WLA object format, try splitting your source into multiple files... so that way each source file can have 255 sections.

I tried that but ran into #269.

> Ville and I have also talked about extending the object format so that cross-CPU object files that share a single address space can be linked together (this is most specific to SNES- 65816 and SPC-700 code will ultimately reside in the same ROM image- but I'm sure there are others)

Or 65816, SPC700, and Game Boy, for Super Game Boy programs that include both GB and SNES native versions of a game.

**Comment by vhelin** [comment]
Sounds like a cool feature to have, mixing different CPU objects in the linker!
