### ISSUE TITLE
Fix no$gmb symbol files for bgb compatibility

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#87]
wlalink outputs:
```
0000:0061 setup
0000:0150 gfx
0000:0538 end_gfx
```

no$gmb takes this and:
```
00:0061 setup
00:0150 gfx
00:0538 end_gfx
```

bgb only takes:
```
00:0061 setup
00:0150 gfx
00:0538 end_gfx
```

Writing the bank as 8-bit rather than 16-bit would work for both these emulators.

**Comment by vhelin** [comment]
I hope it now works. :)

**Comment by nicklausw** [comment]
Yep, it's good. Thanks :+1:
