### ISSUE TITLE
Suggestion: remove the makefiles directory

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#94]
and the amiga files. These should only be in the legacy branch.

**Comment by nicklausw** [comment]
same with msdos.bat.

**Comment by cr1901** [comment]
Made a compromise and created a historical subdirectory, as per Issue #95 and #4.

**Comment by nicklausw** [comment]
Still some makefiles lurking around in wlalink and wlab directories.

**Comment by cr1901** [comment]
Should be fixed.

**Comment by nicklausw** [comment]
Also one more thing that bothers me is wasted space. There's two extra LICENSE files with the same license enclosed in icopy and wlad directories.
