### ISSUE TITLE
Question: what's the deal with icopy?

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#95]
I've never actually noticed the icopy folder before, and the program inside does not seem to serve any purpose; it isn't even referenced in WLA (including the readme) outside the program itself. And also there's a LICENSE file in the icopy folder which just takes up space.

**Comment by cr1901** [comment]
Way back in Issue #4:

> icopy is GB specific and quite a rarely used tool, I guess, WLA DX doesn't
require it, so at least that one can go to such "historical" subdir along
with txt/opcodes.

I've decided to do just that. Make a historical subdirectory.
